export const appOwnedSettingsIssueStatuses = [
  "needs_action",
  "in_progress",
  "resolved",
  "blocked",
  "dismissed",
];
export const appOwnedSettingsSearchProtocol = {
  global_entry_count: 1,
  entry_testid: "settings-search-input",
  scope: "bilingual_item_level_index",
  languages: ["zh-CN", "en"],
  result_label_format: "{page_label} > {entry_label}",
  result_policy: "select_result_navigates_to_owner_route_and_anchor",
  anchor_transport: "route_id_plus_anchor_field_with_section_query_fallback",
  compatibility_index_policy:
    "index_update_theme_local_services_and_personalization_under_owner_page_anchors",
  empty_state: "show_no_matching_settings_without_exposing_internal_route_ids",
};
export const appOwnedSettingsVisualSystem = {
  style: "codex_quiet_control_center_with_opl_information_architecture",
  style_exclusion: "multi_hue_card_dashboard",
  baseline_shell_commit: "409dd0c3b693f1c7c93551654dfac8fb9420843d",
  baseline_comparison_policy:
    "fresh_same_route_screenshots_must_preserve_or_improve_information_hierarchy",
  card_policy: "unframed_sections_with_bounded_groups_only_for_repeated_entities_or_confirmation",
  first_viewport_spatial_group_range: { min: 2, max: 4 },
  nested_cards_allowed: false,
  page_wide_list_wall_allowed: false,
  page_sections_as_floating_cards_allowed: false,
  desktop_group_layout: "single_column_reading_lane",
  mobile_group_layout: "single_column_stack",
  icon_slot_px: 20,
  typography: {
    page_title: "20/28/600",
    card_title: "14-16/20-24/600",
    description: "13/20/400",
    supporting: "12/18/400",
  },
  status_color_semantics: {
    normal: "muted",
    warning: "orange",
    error: "red",
    action: "brand",
  },
  object_accent_policy:
    "use monochrome utility navigation icons and reserve color for typed warning error success and brand actions",
  footer_layout: "compact",
  footer_controls: [
    "gateway_account_or_account_access_entry",
    "app_update_status_and_trigger",
  ],
  footer_account_entry_policy:
    "show_gateway_display_name_when_connected_else_account_access_without_a_duplicate_settings_entry",
  footer_update_entry_policy:
    "show_confirmed_newer_app_update_as_account_row_trailing_action_and_reuse_existing_carrier_updater_without_owning_update_truth",
  footer_theme_quick_toggle_allowed: false,
  footer_secondary_navigation_allowed: true,
  footer_auxiliary_navigation: "about_only_sidebar_bottom",
  footer_duplicate_settings_entry_allowed: false,
  appearance_mode_values: ["system", "light", "dark"],
  appearance_mode_presentation: "three_visual_preview_cards",
  appearance_mode_preserves_theme_preset: false,
  theme_gallery_presentation: "not_exposed",
  theme_swatch_list_allowed: false,
  max_border_radius_px: 8,
  spacing_scale_px: [12, 16, 24],
  heading_density: "compact",
  primary_action_per_page_max: 1,
  normal_state_emphasis: "muted",
  exception_state_emphasis: "accent_only_when_attention_required",
  technical_details_default: "collapsed",
  letter_spacing_px: 0,
};
export const appOwnedSettingsPageExperienceFields = [
  "product_page_id",
  "route_id",
  "matrix_page_id",
  "label_zh",
  "label_en",
  "primary_information",
  "first_viewport_groups",
  "primary_action",
  "exception_state",
  "technical_details_boundary",
  "required_dom",
  "required_anchors",
  "search_entry_ids",
];
export const appOwnedSettingsSearchEntryFields = [
  "id",
  "page_id",
  "anchor",
  "label_zh",
  "label_en",
  "keywords_zh",
  "keywords_en",
];
export const appOwnedSettingsCardFields = [
  "id",
  "title",
  "state",
  "summary",
  "recommended_action",
  "last_checked_at",
  "details_disclosure",
];
export const appOwnedSettingsConfirmationFields = [
  "action_id",
  "summary",
  "will_change",
  "will_not_change",
  "rollback_or_receipt",
  "requires_preview_or_proof",
];
export const appOwnedSettingsPostUpdateNoticeFields = [
  "component_id",
  "result",
  "receipt_ref",
  "next_check",
  "restart_or_reload_guidance",
];
export const appOwnedSettingsMakeUsableAllowedSteps = [
  "run existing repair prep",
  "check managed update status",
  "repair components with explicit repair receipt",
  "apply safe non-restart package or Codex Surface sync actions",
  "refresh fast App state",
];
export const appOwnedSettingsMakeUsableForbiddenSteps = [
  "implement a second updater kernel",
  "write runtime truth, domain truth, owner receipts, or typed blockers",
  "silently apply OPL Runtime Fabric changes that require restart",
  "silently update dirty or developer checkouts",
  "rollback automatically without explicit per-component user confirmation",
];
export const appOwnedSettingsVisualQaTargets = [
  "desktop_settings_overview",
  "desktop_settings_gateway",
  "desktop_settings_models",
  "desktop_settings_workspace",
  "desktop_settings_agents",
  "desktop_settings_capabilities",
  "desktop_settings_resources",
  "desktop_settings_maintenance",
  "desktop_settings_storage",
  "desktop_settings_preferences",
];
export const appOwnedSettingsUpstreamIntakeClassifications = [
  "accepted",
  "adapt",
  "redirect",
  "reject",
];
export const appOwnedSettingsProductSystemItemIds = [
  "control_center_positioning",
  "ten_entry_ia",
  "secondary_route_strategy",
  "compatibility_anchor_routes",
  "single_control_plane",
  "host_adapter_slot",
  "per_page_experience_contracts",
  "view_model_layer",
  "issue_action_protocol",
  "maintenance_noise_reduction",
  "workspace_normal_state",
  "workspace_personalization_owner",
  "gateway_single_owner",
  "model_access_source",
  "capabilities_experience",
  "resources_readiness_boundary",
  "data_storage_safety",
  "owner_storage_projection",
  "preferences_user_language",
  "maintenance_diagnostics",
  "about_update_summary",
  "startup_cache_hydration",
  "managed_dependency_currentness",
  "ownership_no_duplicates",
  "user_copy_system",
  "settings_search",
  "visual_system",
  "screenshot_qa",
  "contract_validators",
  "worktree_lane_hygiene",
  "installed_release_currentness",
];
export const appOwnedSettingsProductSystemTracks = [
  "product_positioning",
  "ia_routes",
  "control_plane",
  "shell_adapter",
  "state_action_protocol",
  "user_task_ux",
  "visual_qa",
  "ops_hygiene",
  "release_currentness",
];
export const legacySettingsRouteRedirects = {
  overview: "general",
  runtime: "environment",
  system: "environment#diagnostics",
  advanced: "environment#diagnostics",
  model: "access",
  agent: "agents",
  assistants: "capabilities#third-party",
  "skills-hub": "capabilities#opl-flow-managed",
  tools: "capabilities#third-party",
  display: "appearance",
  webui: "resources",
  pet: "appearance",
};
