import path from "node:path";
import { fileURLToPath } from "node:url";
import { resolveActiveShellPaths } from "../app-shell-adapter.ts";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const shellPaths = resolveActiveShellPaths();

export type ReleaseBoundaryCheck = {
  id: string;
  file: string;
  required?: string[];
  forbidden?: string[];
  retired?: boolean;
};

export type ReleaseValidationProfile = 'aggregate' | 'stable' | 'windows';

export function releaseValidationProfile(
  value = process.env.OPL_RELEASE_VALIDATION_PROFILE,
): ReleaseValidationProfile {
  if (value === undefined || value === '') return 'aggregate';
  if (value === 'aggregate' || value === 'stable' || value === 'windows') return value;
  throw new Error(`Unsupported OPL_RELEASE_VALIDATION_PROFILE: ${value}.`);
}

export function activeShellReleaseValidationProfile(
  quick: boolean,
  value = process.env.OPL_RELEASE_VALIDATION_PROFILE,
): ReleaseValidationProfile {
  return releaseValidationProfile(
    value === undefined || value === ''
      ? (quick ? 'stable' : 'aggregate')
      : value,
  );
}

export const releaseWorkflowPaths = [
  ".github/workflows/_build-reusable.yml",
  ".github/workflows/_release-bundle.yml",
  ".github/workflows/_release-desktop-platform-addon.yml",
  ".github/workflows/_release-full-addon.yml",
  ".github/workflows/_release-studio-full.yml",
  ".github/workflows/_release-homebrew-full-publish.yml",
  ".github/workflows/_release-standard-publish.yml",
  ".github/workflows/build-manual.yml",
  ".github/workflows/release-diagnostics.yml",
  ".github/workflows/docker-webui-clean-vm.yml",
  ".github/workflows/full-first-install-release.yml",
  ".github/workflows/release-qualification.yml",
  ".github/workflows/opl-first-run-vm.yml",
  ".github/workflows/opl-studio-preview-vm.yml",
  ".github/workflows/release-bundle-canary.yml",
  ".github/workflows/release-manual-full-preview.yml",
  ".github/workflows/release-stable-post-success-followups.yml",
  ".github/workflows/release-nightly.yml",
  ".github/workflows/release-nightly-followups.yml",
  ".github/workflows/release-stable.yml",
  ".github/workflows/release-webui-development.yml",
  ".github/workflows/release-webui-stable.yml",
];

const windowsProfileWorkflowPaths = new Set([
  '.github/workflows/docker-webui-clean-vm.yml',
  '.github/workflows/_build-reusable.yml',
  '.github/workflows/build-manual.yml',
]);

export function releaseWorkflowPathsForProfile(
  profile = releaseValidationProfile(),
): string[] {
  if (profile === 'aggregate') return releaseWorkflowPaths;
  if (profile === 'stable') return releaseWorkflowPaths;
  return releaseWorkflowPaths.filter((workflowPath) => windowsProfileWorkflowPaths.has(workflowPath));
}

const legacyReleaseBoundaryChecks: ReleaseBoundaryCheck[] = [
  {
    id: "local_first_release_preflight",
    file: "scripts/verify.sh",
    required: [
      "release-preflight)",
      "opl_app_local_release_preflight.v1",
      "actionlint",
      "npm run typecheck",
      "npm run validate:active-shell",
      "npm run test:release-boundary",
      "npm run validate:shell-candidates",
      "npm run build-mac:arm64",
      "github_hosted_required_macos_linux_matrix",
      "github_hosted_desktop_release_set_matrix_required",
      "protected_signing_and_notarization_credentials",
      "owner_authoritative_remote_readback",
      "post_publication_clean_machine_certification",
      "public_mutation_allowed: false",
    ],
    forbidden: [
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
      "gh release create",
    ],
  },
  {
    id: "optional_certification_receipt_contract",
    file: "contracts/app-optional-certification-receipt.schema.json",
    required: [
      "opl_app_optional_certification_receipt.v1",
      "\"passed\"",
      "\"failed\"",
      "\"not_run\"",
      "\"unavailable\"",
      "\"required_for_publication\"",
      "\"component_manifest_resigned\"",
    ],
  },
  {
    id: "optional_certification_receipt_validator",
    file: "scripts/validate-optional-certification-receipt.ts",
    required: [
      "passed",
      "failed",
      "not_run",
      "unavailable",
      "certification must never rebuild the artifact",
      "certification must not mutate the component manifest",
      "queued, runner inventory, authentication, or network state cannot prove unavailable",
    ],
  },
  {
    id: "retired_standalone_webui_publish_helper_absent",
    file: "scripts/webui-ghcr-release-step.sh",
    retired: true,
  },
  {
    id: "release_contract_repo",
    file: "contracts/app-release-channel.json",
    required: [
      '"release_repo": "gaofeng21cn/one-person-lab-app"',
      '"source_freeze_currentness_policy"',
      '"remote_and_current_authority_read_mode": "single_cutoff_read"',
      '"canonical_live_catalog_equality_is_prebuild_precondition": false',
      '"host_installed_or_effective_state_is_prebuild_precondition": false',
      '"module_main_or_tag_advancement_triggers_rebuild": false',
      '"explicit security revocation bound to the frozen ref or digest"',
    ],
    forbidden: ['"release_repo": "gaofeng21cn/one-person-lab"'],
  },
  {
    id: "update_bridge_repo",
    file: path.relative(
      appRoot,
      path.join(shellPaths.shellRoot, "packages/desktop/src/process/bridge/updateBridge.ts"),
    ),
    required: ["'gaofeng21cn/one-person-lab-app'"],
    forbidden: ["const DEFAULT_REPO = 'gaofeng21cn/one-person-lab'"],
  },
  {
    id: "application_bridge_repo",
    file: path.relative(
      appRoot,
      path.join(
        shellPaths.shellRoot,
        "packages/desktop/src/process/bridge/applicationBridgeCore.ts",
      ),
    ),
    required: ["'gaofeng21cn/one-person-lab-app'"],
    forbidden: ["|| 'gaofeng21cn/one-person-lab'"],
  },
  {
    id: "first_run_vm_download_repo",
    file: ".github/workflows/opl-first-run-vm.yml",
    required: [
      '--repo "$GITHUB_REPOSITORY"',
      "One-Person-Lab-Full-*-mac-arm64.dmg",
      "One-Person-Lab-*-mac-arm64.dmg",
      "release_artifact_name:",
      "release_artifact_run_id:",
      "artifact_app_ref:",
      "verification_app_ref:",
      "smoke_harness_ref:",
      "framework_ref:",
      "framework_sha: ${{ steps.framework_ref.outputs.framework_sha }}",
      "Validate Framework ref before VM runner work",
      "ref: ${{ inputs.verification_app_ref || inputs.artifact_app_ref || github.sha }}",
      "verification_app_sha: ${{ steps.verification_app.outputs.app_sha }}",
      "persist-credentials: false",
      'verification_app_sha="$(git rev-parse HEAD)"',
      "ref: ${{ steps.smoke_harness_ref.outputs.shell_sha }}",
      "ref: ${{ steps.framework_ref.outputs.framework_sha }}",
      "Build exact clean VM source handoff",
      "Upload exact clean VM source handoff",
      "Download exact clean VM source handoff",
      "Activate exact clean VM sources",
      "name: opl-clean-vm-sources-${{ inputs.package_profile }}-${{ github.run_id }}",
      'test "$(git rev-parse HEAD)" = \'${{ needs.validate-vm-inputs.outputs.verification_app_sha }}\'',
      '--app-sha "${{ needs.validate-vm-inputs.outputs.artifact_app_sha }}"',
      '--shell-sha "${{ needs.validate-vm-inputs.outputs.shell_sha }}"',
      '--verification-app-sha "$verification_app_sha"',
      '--verification-app-sha "${{ steps.verification_app.outputs.app_sha }}"',
      '--verification-shell-sha "${{ needs.validate-vm-inputs.outputs.smoke_harness_sha }}"',
      'scripts/qualification-harness-scope.ts',
      '--verification-scope-proof-base64',
      "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c",
      "run-id: ${{ inputs.release_artifact_run_id || github.run_id }}",
      "Using same-run workflow artifact",
      "Using source workflow run artifact",
      "Checkout exact Framework bootstrap source for VM handoff",
      "repository: gaofeng21cn/one-person-lab",
      "Prepare OPL Framework bootstrap archive",
      "git -C one-person-lab archive --format=tar.gz --prefix=one-person-lab/",
      'CMD+=(--framework-source-archive "${{ steps.framework_source.outputs.archive_path }}")',
      'CMD+=(--framework-install-script "${{ steps.framework_source.outputs.install_script_path }}")',
      "fetch_release_metadata_with_retry()",
      "Release metadata fetch failed on attempt $attempt",
      "download_asset_with_retry()",
      "download_release_with_retry()",
      "Resolved release DMG asset: $asset_name",
      "Release DMG asset download failed on attempt $attempt",
      "asset.apiUrl || asset.url",
      "Accept: application/octet-stream",
      "Authorization: Bearer ${GH_TOKEN}",
      "curl_args=(-fL --retry 5 --retry-all-errors --retry-delay 10 --connect-timeout 30 --max-time 1800 --continue-at -)",
      "fetch-depth: 1",
      "filter: blob:limit=1m",
      "sparse-checkout: |",
      "/scripts/",
      "/packages/desktop/src/common/config/oplProductProfile/oplProductProfile.generated.json",
      "sparse-checkout-cone-mode: false",
      "package_profile:",
      "diagnostic_scope:",
      "diagnostic_scope != 'bootstrap_only'",
      "Resolve package profile",
      "--smoke-profile no-clt-clean-vm",
      "--display 1920x1080px",
      "--settings-smoke",
      "--assistant-route-smoke",
      "--codex-functional-check",
      "--codex-ai-self-check",
      '--runtime-profile "${{ steps.package_profile.outputs.runtime_profile }}"',
      "guide_screenshots:",
      "CMD+=(--guide-screenshots)",
    ],
    forbidden: [
      "--repo gaofeng21cn/one-person-lab",
      '--app-sha "$GITHUB_SHA"',
      "ref: ${{ needs.validate-vm-inputs.outputs.shell_sha }}",
      "'/packages/*/package.json'",
      "Materialize active shell dependency metadata",
      "git -C shells/aionui sparse-checkout set",
      "Setup bun",
      "Install active shell harness dependencies",
      "bun install --frozen-lockfile --ignore-scripts",
    ],
  },
  {
    id: "studio_preview_vm_qualification_workflow",
    file: ".github/workflows/opl-studio-preview-vm.yml",
    required: [
      "name: OPL Studio Preview VM Qualification",
      "verification_source_ref:",
      "release_source_sha:",
      "framework_ref:",
      "standard_asset_digest:",
      "full_asset_digest:",
      "git/ref/heads/main",
      "runs-on: [self-hosted, macOS, ARM64, opl-cert-mac-tart]",
      "profile: [standard, full]",
      "max-parallel: 1",
      "scripts/desktop/qualify-clean-vm.mjs",
      "opl-release-manifest.json",
      "Checkout exact Framework bootstrap source",
      "Prepare exact Framework bootstrap input",
      "--framework-source-archive",
      "--framework-ref",
      "--continue-at -",
      "--require-gateway-setup",
      "--require-codex-turn",
      "--screenshots-dir",
      "OPL_GATEWAY_RELEASE_TEST_ACCOUNT_EMAIL",
      "OPL_GATEWAY_RELEASE_TEST_ACCOUNT_PASSWORD",
      "Reject protected credentials in evidence",
      "steps.evidence-scan.outcome == 'success'",
      "Remove downloaded public DMG from evidence",
      "opl_app_studio_preview_vm_qualification.v1",
    ],
    forbidden: [
      "contents: write",
      "packages: write",
      "gh release create",
      "gh release upload",
      "gh release edit",
      "gh release delete",
      "--clobber",
      "make_latest",
    ],
  },
  {
    id: "full_dmg_notarizer_uses_system_default_timestamp",
    file: "scripts/notarize-macos-dmg.ts",
    required: [
      "const timestampAuthoritySelection = 'system_default'",
      "['--force', '--timestamp', '--sign', identity, probePath]",
      "['--force', '--timestamp', '--sign', identity, candidateDmg]",
    ],
    forbidden: [
      "timestamp.apple.com",
      "--timestamp=",
    ],
  },
  {
    id: "docker_webui_clean_vm_workflow",
    file: ".github/workflows/docker-webui-clean-vm.yml",
    required: [
      "name: OPL Docker WebUI Clean VM Smoke",
      "workflow_dispatch:",
      "platform:",
      "- linux",
      "- windows",
      "clean-linux-vm-smoke:",
      "if: ${{ inputs.platform == 'linux' }}",
      "runs-on: ubuntu-latest",
      "docker-webui-clean-linux-vm-evidence",
      "--gate clean_linux_vm",
      "--validate-result docker-webui-clean-linux-vm/docker-webui-smoke-gate-result.json",
      "runner_labels_json:",
      "runner_inventory_json:",
      '["self-hosted","Windows","X64","docker-webui-clean-vm"]',
      "runner-preflight:",
      "runs-on: ubuntu-latest",
      "workflow_dispatch_input",
      "RUNNER_INVENTORY_JSON",
      "repos/${process.env.GITHUB_REPOSITORY}/actions/runners",
      "runner_inventory_unreadable",
      "missing_clean_windows_self_hosted_runner",
      "docker-webui-clean-windows-vm-runner-blocker",
      "needs: runner-preflight",
      "if: ${{ inputs.platform == 'windows' && needs.runner-preflight.result == 'success' }}",
      "runs-on: ${{ fromJSON(inputs.runner_labels_json) }}",
      "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true",
      "ghcr.io/gaofeng21cn/one-person-lab-webui:latest",
      "artifact_name:",
      "docker-webui-clean-windows-vm-evidence",
      "powershell -ExecutionPolicy Bypass",
      "-File scripts/install-docker-webui.ps1",
      "-EvidenceDir windows-clean-evidence",
      "-EvidenceArchive windows-clean-evidence.zip",
      "node --experimental-strip-types scripts/docker-webui-smoke-gate.ts",
      "--gate clean_windows_vm",
      "--evidence windows-clean-evidence.zip",
      "--validate-result docker-webui-clean-windows-vm/docker-webui-smoke-gate-result.json",
      "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a",
      "docker compose -f $composePath down --remove-orphans",
    ],
    forbidden: [
      "--gate existing_docker",
      "runs-on: windows-latest",
      "packages: write",
      "OPENAI_API_KEY",
      "GHCR_TOKEN",
    ],
  },
  {
    id: "docker_webui_clean_windows_dispatch_helper",
    file: "scripts/dispatch-docker-webui-clean-windows-smoke.ts",
    required: [
      "opl_docker_webui_clean_windows_dispatch_plan.v1",
      "runner_inventory_json",
      "missing_clean_windows_self_hosted_runner",
      "docker-webui-clean-vm.yml",
      "actions/runners",
      "workflow",
      "run",
      "--execute",
    ],
  },
  {
    id: "docker_webui_clean_windows_dispatch_npm_script",
    file: "package.json",
    required: [
      "smoke:docker-webui:windows-clean-vm:dispatch",
      "scripts/dispatch-docker-webui-clean-windows-smoke.ts",
    ],
  },
  {
    id: "docker_webui_clean_windows_runner_bootstrap_runbook",
    file: "docs/delivery/install/docker-webui-smoke-gates.md",
    required: [
      "Clean Windows Runner Bootstrap",
      "self-hosted",
      "Windows",
      "X64",
      "docker-webui-clean-vm",
      "Docker Desktop",
      "WSL 2",
      "Settings -> Actions -> Runners -> New",
      "Keep the generated registration token out of docs",
      "npm run smoke:docker-webui:windows-clean-vm:dispatch -- --execute --json",
      "docker-webui-clean-windows-vm-evidence",
      "docker_webui_clean_windows_evidence_artifact",
      "docker-webui-clean-windows-vm-runner-blocker",
      "missing_clean_windows_self_hosted_runner",
      "runner_inventory_unreadable",
    ],
    forbidden: [
      "windows-latest runner is acceptable evidence",
      "registration token:",
      "OPENAI_API_KEY",
      "GHCR_TOKEN",
    ],
  },
  {
    id: "release_notes_ai_provider_chain",
    file: "scripts/release-notes-ai-writer.ts",
    required: [
      "OPL_RELEASE_NOTES_PROVIDER",
      "openai_compatible",
      "--probe-openai-compatible",
      "OPL_RELEASE_NOTES_AI_TIMEOUT_SECONDS",
      "OPL_RELEASE_NOTES_OPENAI_COMPATIBLE_BASE_URL",
      "OPL_RELEASE_NOTES_OPENAI_COMPATIBLE_API_KEY",
      "OPL_RELEASE_NOTES_CODEX_BASE_URL",
      "OPL_RELEASE_NOTES_CODEX_API_KEY",
      "OPL_RELEASE_NOTES_MODEL",
      "envValue",
      "OpenAI-compatible provider failed",
      "No online OpenAI-compatible release-note provider is configured.",
      "runCodexProvider",
      "validateAiReleaseNotes",
      "self-referential release-note copy",
      "opening paragraph is process-first",
      "missing opening user benefit paragraph before sections",
      "payload lines formatted as blockquotes",
      "developer memo terms before Technical details",
      "payload ref before Technical details",
      "## Technical details",
      "missing user-facing MAS/MAG/RCA role descriptions",
      "missing concrete runtime change detail",
      "## Install Stable",
      "missing Stable install command",
    ],
    forbidden: [],
  },
  {
    id: "release_notes_agent_runtime_evidence",
    file: "scripts/release-notes/payload.ts",
    required: [
      "buildAgentRuntimeChanges",
      "collectComponentChangeSubjects",
      "research automation and study workflow agent",
      "grant-writing and funding workflow agent",
      "visual deliverable, slide, and report graphics agent",
    ],
    forbidden: [],
  },
  {
    id: "release_notes_agent_runtime_output",
    file: "scripts/release-notes.ts",
    required: [
      "agent_runtime_changes",
      "buildAgentRuntimeChanges",
      "install_command",
      "brew install --cask gaofeng21cn/one-person-lab/one-person-lab",
    ],
    forbidden: [],
  },
  {
    id: "homebrew_tap_boundary_script",
    file: "scripts/update-homebrew-tap.ts",
    required: [
      "manifest_required: true",
      "checksum_required: true",
      "nightly_targets_only_for_nightly: true",
      "stable_promotion_from_nightly_allowed: false",
      "full_first_install_allowed: false",
      "full_first_install_allowed: true",
      "standard_updater_visible: false",
      "bundled_full_runtime_payload_allowed: true",
      "homebrew_allowed_software_objects: opl_base,opl_app",
      "opl_packages_lifecycle_owned_by_homebrew: false",
      "opl_packages_lifecycle_owner: one-person-lab",
      "opl_packages_lifecycle_command: opl packages",
      "package_specific_formula_allowed: false",
      "package_specific_cask_allowed: false",
      "forbidden_package_formulae: mas,mag,rca,oma,obf,mas-scholar-skills,opl-flow",
      "forbidden_package_casks: mas,mag,rca,oma,obf,mas-scholar-skills,opl-flow",
      "publishes_or_pushes_remote: false",
      "app_full_first_install",
      "Nightly Homebrew tap updates may only update the Nightly App cask target.",
      "Nightly Homebrew tap updates must use YY.M.D-nightly or YY.M.D-nightly.r1 through .r9.",
      "Stable Homebrew tap updates must use YY.M.D or YY.M.D-r1 through r9.",
      "Full first-install Homebrew cask updates must stay on the stable channel.",
      "Full first-install Homebrew cask updates may only update Casks/one-person-lab-full.rb.",
      "Homebrew tap updates are App cask-only; OPL Packages are Framework-managed, not Homebrew formulae.",
      "must not reference Full first-install payloads",
    ],
    forbidden: ["from 'node:child_process'", "spawnSync(", "execSync(", "execFileSync("],
  },
  {
    id: "homebrew_tap_package_scripts",
    file: "package.json",
    required: [
      '"homebrew:tap:plan": "node --experimental-strip-types scripts/update-homebrew-tap.ts"',
      '"validate:homebrew-tap": "node --experimental-strip-types scripts/update-homebrew-tap.ts --self-check"',
      '"release:nightly-version:resolve": "node --experimental-strip-types scripts/resolve-nightly-version.ts"',
      '"release:actions-timing": "node --experimental-strip-types scripts/summarize-github-actions-timing.ts"',
      '"release:readiness-summary": "node --experimental-strip-types scripts/summarize-release-readiness.ts"',
      '"release:full:prune-audit": "node --experimental-strip-types scripts/audit-full-runtime-prune-policy.ts"',
    ],
    forbidden: [],
  },
  {
    id: "full_runtime_prune_policy_contract",
    file: "contracts/full-runtime-prune-policy.json",
    required: [
      '"schema": "opl_full_runtime_prune_policy.v1"',
      '"id": "full_runtime_offline_first_install_slim_v1"',
      '"source": "Docker build context"',
      '"source": "npm pack dry-run"',
      '"source": "electron-builder application contents"',
      '"runtime_tree"',
      '"production_node_modules"',
      '"node_toolchain_global_packages"',
      '"app_bundle_staging"',
      '"runtime_assertions"',
      '"required_built_exports"',
      '"validation_examples"',
      '"audit_command": "npm run release:full:prune-audit -- --markdown"',
    ],
    forbidden: ["TODO", "TBD", "2c7fad262938fb4295d2bb866f6b955c0aa2361a"],
  },
  {
    id: "full_runtime_prune_policy_audit_script",
    file: "scripts/audit-full-runtime-prune-policy.ts",
    required: [
      "opl_full_runtime_prune_policy_audit.v1",
      "contracts/full-runtime-prune-policy.json",
      "validation_examples",
      "runtime_scan_diff",
      "--runtime-root",
      "--baseline",
      "collectRuntimeAssertions",
    ],
    forbidden: ["TODO", "TBD"],
  },
  {
    id: "release_actions_timing_script",
    file: "scripts/summarize-github-actions-timing.ts",
    required: [
      "opl_github_actions_timing_summary.v1",
      "gh run view",
      "--json",
      "failed_or_cancelled_run_wall_seconds",
      "unaccounted_operator_seconds",
      "top_jobs",
      "top_steps",
    ],
    forbidden: ["gh run watch", "gh run download"],
  },
  {
    id: "release_candidate_record_validator_script",
    file: "scripts/validate-release-candidate-record.ts",
    required: [
      "opl_app_historical_release_candidate_inspection.v1",
      "opl_release_candidate_record.v1",
      "ready_to_promote",
      "historical_read_only",
      "authoritative_for_new_release: false",
      "promote_ready: false",
      "mutation_authorized: false",
      "framework_opl_release_portable_checkpoint_and_receipt",
      "opl_release_bundle_checkpoint.v1",
      "opl_release_bundle_executor_receipt.v1",
      "opl release status --bundle <sha256:digest> --store <directory>",
      "inspect_framework_checkpoint_and_receipts",
      "--promote-ready",
      "--status",
    ],
    forbidden: ["TODO", "TBD", "receipt-gated", "release:stable -- promote", "--execute"],
  },
  {
    id: "reusable_build_gatekeeper_policy",
    file: ".github/workflows/_build-reusable.yml",
    required: [
      "macos-signing-preflight:",
      "name: macOS release signing preflight",
      "runs-on: macos-latest",
      "Import Developer ID identity and authenticate notarization",
      "scripts/verify-apple-release-credentials.ts",
      "Upload sanitized Apple credential preflight receipt",
      "opl-apple-release-credentials-preflight-${{ github.run_id }}",
      "require_macos_gatekeeper:",
      "OPL_REQUIRE_MACOS_GATEKEEPER",
      "Write macOS Stable local authorization policy",
      "Ensure macOS standard updater ZIP distributable",
      "Finalize Standard Developer ID signing and notarization",
      "Verify Standard final distribution trust",
      'expected_zip="One-Person-Lab-${OPL_RELEASE_VERSION}-mac-${target_arch}.zip"',
      'expected_zip_blockmap="${expected_zip}.blockmap"',
      "Missing standard updater ZIP",
      "Missing standard updater ZIP blockmap",
      "--mac dmg zip",
      '--prepackaged "$app_path"',
      'grep -q "$expected_zip" "$metadata"',
      'spctl --assess --type execute --verbose=4 "$app_path"',
      "standard-local-authorization-policy.json",
      "standard-gatekeeper-launch-policy.json",
      "standard-apple-notarization-receipt.json",
      "scripts/notarize-macos-dmg.ts",
      "scripts/update-electron-updater-metadata.ts",
      "--package-kind app_standard",
    ],
    forbidden: [
      "opl_flow_ref:",
      "name: Checkout OPL Flow policy source",
      "repository: gaofeng21cn/opl-flow",
      "OPL_FLOW_WORKFLOW_POLICY",
      "OPL_FULL_OPL_FLOW_ROOT",
    ],
  },
  {
    id: "apple_release_credentials_preflight_script",
    file: "scripts/verify-apple-release-credentials.ts",
    required: [
      "opl_apple_release_credentials_preflight.v1",
      "Apple release credential preflight requires a macOS runner.",
      "create-keychain",
      "set-key-partition-list",
      "find-identity",
      "--timestamp",
      "--options",
      "runtime",
      "TeamIdentifier mismatch",
      "notarytool",
      "history",
      "admission_eligible",
      "first-attempt workflow_dispatch on canonical App main",
      "submission_performed: false",
      "notarySubmissionId",
      "notarytool', 'info'",
      "notarization_resume_performed: false",
      "notarization_staple_performed: false",
      "release_dispatch_performed: false",
      "public_asset_write_performed: false",
      "canonical_main_credential_runtime_preflight_not_release_or_artifact_qualification",
      "<redacted>",
    ],
    forbidden: [
      "notarytool submit",
      "release create",
      "release upload",
      "contents: write",
      "packages: write",
    ],
  },
  {
    id: "stable_release_admission_manifest",
    file: "scripts/stable-release-admission-manifest.ts",
    required: [
      "opl_stable_release_admission_manifest.v1",
      "requiredSecretNames",
      "validateReleaseHomebrewDistribution",
      "resolveStableReleaseVersion",
      "assertPromotionTargetIsNewerThanPublishedStable",
      "anonymousWebuiTags",
      "activeReleaseStatuses",
      "parseGitHubJsonLookup",
      "readOwnerWorkflowRuns",
      "raw_standard_version_or_ref_inputs_allowed: false",
      "read_only_reconcile_without_rerun_redispatch_or_cancel",
      "manifest_digest",
    ],
    forbidden: [
      "gh workflow run",
      "gh release create",
      "gh release upload",
      "gh run rerun",
      "gh run cancel",
      "git push",
    ],
  },
  {
    id: "release_dispatch_guard",
    file: "scripts/release-dispatch-guard.ts",
    required: [
      "opl_release_dispatch_guard.v1",
      "['ls-remote'",
      "logical_query_count: 1",
      "tls_handshake_timeout",
      "unexpected_eof",
      "credential_failure",
      "node_structured_json_without_jq",
      "operationStartedAt",
      "mutation_retry_count: 0",
      "read_only_reconcile_only: true",
      "replacement_allowed: false",
      "redispatch_allowed: false",
    ],
    forbidden: [
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
      "gh release create",
      "gh release edit",
      "gh release upload",
      "gh release delete",
      "git push",
    ],
  },
  {
    id: "shell_product_profile_consumer_gate",
    file: "scripts/validate-shell-product-profile-consumer.ts",
    required: [
      "opl_shell_product_profile_consumer_gate.v1",
      "temporary_exact_shell_archive",
      "tests/unit/common-config/oplProductProfile.test.ts",
      "syncAppProductProfileToShell",
      "source_shell_mutated: false",
    ],
    forbidden: [
      "gh workflow run",
      "git push",
      "release create",
    ],
  },
  {
    id: "release_diagnostics_hub",
    file: ".github/workflows/release-diagnostics.yml",
    required: [
      "name: OPL Release Diagnostics",
      "workflow_call:",
      "workflow_dispatch:",
      "diagnostic:",
      "- desktop",
      "- apple_credentials",
      "- timestamp_authority",
      "contents: read",
      "actions: read",
      "diagnostic-inputs:",
      "release-diagnostics:",
      "uses: ./.github/workflows/opl-first-run-vm.yml",
      "apple-credentials:",
      "large_dmg_canary:",
      "notary_submission_id:",
      "runs-on: macos-latest",
      "timeout-minutes: 45",
      "environment: release-stable",
      "ref: ${{ github.sha }}",
      "node-version: '24'",
      "scripts/verify-apple-release-credentials.ts",
      "--large-dmg-canary",
      "--notary-submission-id",
      "Upload sanitized Apple credential preflight receipt",
      "if: ${{ always() }}",
      "Stable admission authority: false",
      "timestamp-authority:",
      "scripts/diagnose-apple-timestamp-authority.ts",
      "retention-days: 30",
    ],
    forbidden: [
      "contents: write",
      "packages: write",
      "actions: write",
      "gh workflow run",
      "gh release create",
      "gh release edit",
      "gh release upload",
      "gh release delete",
      "git push",
      "notarytool submit",
    ],
  },
  {
    id: "release_asset_local_authorization_verifiers",
    file: "scripts/verify-remote-release-assets.ts",
    required: [
      "opl-release-attestation.json",
      "full-local-authorization-policy.json",
      "full-runtime-currentness-probe.json",
      "full-runtime-native-trust.json",
      "assertStandardDistributionTrust",
      "assertStandardUpdaterAppBundleTrust",
      "standardUpdaterAppBundleTrust",
      "standard_updater_app_bundle_trust",
      "apple_developer_id_required",
      "gatekeeper_required",
      "notarization_receipt_sha256",
      "TeamIdentifier",
      "Signature",
      "Developer ID Application:",
      "assertFullRuntimeNativeTrust",
      "spctl_status",
      "codesign_status",
      "stapler",
    ],
    forbidden: [],
  },
  {
    id: "first_run_vm_local_authorization_policy",
    file: path.relative(
      appRoot,
      path.join(shellPaths.shellRoot, "scripts/opl-first-run-vm-smoke.mjs"),
    ),
    required: [
      "xattr', ['-dr', 'com.apple.quarantine', targetApp]",
      "gatekeeper-launch-policy.json",
      "gatekeeper_required: gatekeeperRequired",
      "quarantine_removal_required: !gatekeeperRequired",
      "const homebrewFullCask = installOrigin === 'homebrew_full_cask'",
      "const gatekeeperRequired = hooks.requireGatekeeper === true || homebrewFullCask",
      "quarantine_mutation_performed: gatekeeperRequired ? false : null",
      "local_authorization_status: localAuthorizationStatus",
      "'rejected_allowed_unsigned'",
      "'failed_allowed_unsigned'",
      "(hooks.countQuarantineAttributes ?? countQuarantineAttributes)(appPath)",
      "hooks.countQuarantineAttributes ?? countQuarantineAttributes",
      "quarantine_attribute_count: quarantineAttributeCount",
      "if (!gatekeeperRequired && quarantineAttributeCount !== 0)",
      "if (gatekeeperRequired && spctl.status !== 0)",
      "Production App failed the blocking Gatekeeper assessment before first launch.",
      "if (!options.requireGatekeeper)",
    ],
    forbidden: [
      "if (codesign.status !== 0)",
      "if (codesign.status !== 0 || spctl.status !== 0)",
      "Gatekeeper launch policy rejected the packaged app before first launch.",
    ],
  },
  {
    id: "first_run_vm_runtime_refresh_production_evidence",
    file: path.relative(
      appRoot,
      path.join(shellPaths.shellRoot, "scripts/opl-first-run-vm-smoke.mjs"),
    ),
    required: [
      "function buildRuntimeRefreshProbePlan(requestedHash, timeoutMs = DEFAULT_RUNTIME_REFRESH_TIMEOUT_MS)",
      "requestedHash === '#/settings/runtime'",
      "mode: 'settings-maintenance-updates'",
      "aliasResolvedHash: '#/settings/environment'",
      "refreshHash: '#/settings/environment?section=updates'",
      "function settingsRuntimeAliasResolutionExpression(requestedHash, aliasResolvedHash)",
      "function settingsMaintenanceUpdatesReadinessExpression(refreshHash)",
      "function settingsUpdatesRefreshButtonIdleExpression()",
      "function settingsUpdatesRefreshClickExpression()",
      "const selector = '[data-testid=\"opl-managed-update-refresh\"]'",
      "requestedHash === '#/runtime'",
      "mode: 'runtime-v2'",
      "resolvedHashPrefixes: ['#/runtime']",
      "async function exerciseRuntimeRefresh(client, targetHash, timeoutMs = DEFAULT_RUNTIME_REFRESH_TIMEOUT_MS)",
      "settingsRuntimeAliasResolutionExpression(probePlan.requestedHash, probePlan.aliasResolvedHash)",
      "settingsMaintenanceUpdatesReadinessExpression(probePlan.refreshHash)",
      "settingsUpdatesRefreshClickExpression()",
      "requested_hash: targetHash",
      "alias_resolved_hash: aliasResolution.aliasResolvedHash ?? aliasResolution.hash",
      "resolved_hash: resolvedHash",
      "const runtimeRefreshTimeoutMs = Math.min(",
      "options.codexReadinessPhaseTimeoutMs ?? options.timeoutMs",
      "const settingsRuntimeRefresh = await (hooks.exerciseRuntimeRefresh ?? exerciseRuntimeRefresh)(",
      "'#/settings/runtime',",
      "id: 'runtime-settings-alias'",
      "const standaloneRuntimeRefresh = await (hooks.exerciseRuntimeRefresh ?? exerciseRuntimeRefresh)(",
      "'#/runtime',",
      "id: 'runtime-status'",
    ],
    forbidden: [],
  },
  {
    id: "first_run_vm_profile_aware_assistant_smoke",
    file: path.relative(
      appRoot,
      path.join(shellPaths.shellRoot, "scripts/opl-first-run-vm-smoke.mjs"),
    ),
    required: [
      "homeAssistantStandardLaunchAdmissionExpression",
      "homeAssistantWorkspaceContextExpression",
      "homeAssistantRouteSendWithoutActivationExpression",
      "frameworkStageRuntimeActivationExpression",
      "activeConversationRouteReceiptExpression",
      "data-opl-workspace-selected",
      "data-opl-workspace-path",
      "options.runtimeProfile !== 'full'",
      "verification_mode: 'state_aware_launch_admission'",
      "verification_mode: 'route_receipt'",
      "workspace_guid_ui_send_without_shell_activation_then_conversation_get",
      "home-starter-${id}",
      "assistant_launch_admissions_checked",
      "not_applicable_standard",
    ],
    forbidden: [
      "createAssistantRouteReceiptConversationExpression",
      "POST /api/conversations",
    ],
  },
  {
    id: "one_shot_unsigned_local_authorization",
    file: "install.sh",
    required: [
      "--stable-macos-install",
      "STABLE_MACOS_PACKAGE_PROFILE=${OPL_STABLE_MACOS_PACKAGE_PROFILE:-full}",
      "resolve_latest_release_tag()",
      "release_asset_name()",
      "download_or_use_dmg()",
      "download_and_validate_component_manifest()",
      "Release quality: Preview (Dev)",
      "Release quality: Preview (Nightly)",
      "Release quality: not asserted for a custom DMG source.",
      "Component manifest does not bind one exact Standard DMG artifact",
      "Latest pointer selects this exact release but does not change its declared quality.",
      "copy_app_from_dmg()",
      "Mounted DMG must contain exactly one App bundle",
      "stable_macos_install()",
      "Stable macOS App install is currently supported only on macOS arm64.",
      "hdiutil attach -nobrowse -readonly",
      'ditto "$source_app" "$OPL_LOCAL_APP_PATH"',
      "run_with_sudo_fallback",
      "--authorize-local-app-only",
      "--authorize-local-app",
      "--app-path",
      "OPL_LOCAL_APP_PATH=${OPL_LOCAL_APP_PATH:-/Applications/One Person Lab.app}",
      'Type "authorize" to continue',
      'xattr -dr com.apple.quarantine "$OPL_LOCAL_APP_PATH"',
      'codesign --verify --deep --strict --verbose=2 "$OPL_LOCAL_APP_PATH"',
      'spctl --assess --type execute --verbose=4 "$OPL_LOCAL_APP_PATH"',
      "quarantine_before",
      "quarantine_after",
      "One Person Lab macOS App install finished.",
    ],
    forbidden: [],
  },
  {
    id: "install_exposure_unsigned_and_temporal_policy",
    file: "contracts/app-install-exposure-policy.json",
    required: [
      '"surface": "stable_local_authorized_macos_install"',
      '"entrypoint": "install.sh --stable-macos-install --yes"',
      '"compatibility_entrypoints": []',
      '"retired_entrypoints"',
      '"compatibility_wrapper_status": "retired"',
      '"install-stable.sh"',
      '"release_quality_source": "exact_component_manifest"',
      '"latest_pointer_is_quality_independent": true',
      '"non_stable_disclosure_before_target_mutation": true',
      '"legacy_component_manifest_policy": "allow_only_published_non_prerelease_pre_v3_manifest_with_quality_unasserted_disclosure"',
      '"default_package_profile": "full"',
      '"hdiutil attach -nobrowse -readonly"',
      '"ditto"',
      '"open"',
      '"surface": "unsigned_local_app_authorization"',
      '"entrypoint": "install.sh --authorize-local-app-only"',
      '"xattr -dr com.apple.quarantine"',
      '"codesign --verify --deep --strict --verbose=2"',
      '"spctl --assess --type execute --verbose=4"',
      '"auto_configuration_entrypoints"',
      '"opl system startup-maintenance"',
      '"must_export_local_defaults_before_provider_checks": true',
      '"must_surface_service_worker_and_dependency_diagnostics": true',
      '"must_not_block_ready_to_launch_on_worker_residency": true',
      '"must_fail_closed_when_packaged_temporal_payload_is_missing": true',
    ],
    forbidden: [],
  },
  {
    id: "release_qualification_workflow",
    file: ".github/workflows/release-qualification.yml",
    required: [
      "name: OPL Release Qualification",
      "workflow_dispatch:",
      "permissions:",
      "contents: read",
      "name: App release-boundary tests",
      "runs-on: ubuntu-latest",
      "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1",
      "uses: ./.github/actions/setup-active-shell-deps",
      "install-dependencies: 'true'",
      "name: Checkout OPL Flow policy source",
      "ref: 2c7fad262938fb4295d2bb866f6b955c0aa2361a",
      "OPL_FLOW_WORKFLOW_POLICY: ${{ github.workspace }}/opl-flow/contracts/workflow-policy.json",
      "OPL_FULL_OPL_FLOW_ROOT: ${{ github.workspace }}/opl-flow",
      "tests/release/windows-stable-surface.test.ts",
      "npm run test:release-boundary",
      "npm run validate:release-boundary",
    ],
    forbidden: [
      "contents: write",
      "packages: write",
      "actions: write",
      "gh release",
      "npm run release:publish",
      "npm run release:full",
      "npm run build",
      "npm run package",
      "uses: ./.github/workflows/_build-reusable.yml",
      "uses: ./.github/workflows/full-first-install-release.yml",
      "uses: ./.github/workflows/desktop-release.yml",
      "push:",
      "pull_request:",
    ],
  },
  {
    id: "windows_updater_package_validation_workflow",
    file: ".github/workflows/windows-updater-package-validation.yml",
    required: [
      "name: Windows Updater Package Validation",
      "workflow_dispatch:",
      "shell_ref:",
      "framework_ref:",
      "permissions:",
      "contents: read",
      "persist-credentials: false",
      "runs-on: windows-latest",
      "Build updater-capable Windows x64 package",
      "config.nsis.differentialPackage=true",
      "validate-windows-updater-assets.ts",
      "One-Person-Lab-${{ inputs.release_version }}-win-x64.exe.blockmap",
      "latest.yml",
      "opl-windows-updater-assets.json",
      "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a",
      "Upload non-published updater validation assets",
    ],
    forbidden: [
      "contents: write",
      "packages: write",
      "actions: write",
      "secrets: inherit",
      "GH_TOKEN",
      "GITHUB_TOKEN",
      "gh release",
      "gh api",
      "make_latest",
      "uses: ./.github/workflows/_build-reusable.yml",
      "Get-AuthenticodeSignature",
      "opl-windows-authenticode-receipt.json",
      "npm run release:publish",
      "config.publish.provider=generic",
      "config.publish.url=",
    ],
  },
  {
    id: "full_runtime_cache_warmup_is_reusable_capability",
    file: ".github/workflows/full-first-install-release.yml",
    required: [
      "workflow_call:",
      "cache_only:",
      "Warm and validate Full runtime layer caches without building release assets",
      "force_rebuild_runtime_cache:",
      "if: ${{ !inputs.cache_only }}",
      "if: ${{ inputs.cache_only }}",
      "mode='cache_only_warmup'",
    ],
    forbidden: ["workflow_dispatch:"],
  },
];


export const releaseBoundaryChecks: ReleaseBoundaryCheck[] = [
  ...legacyReleaseBoundaryChecks,
  {
    id: "audited_manual_build_and_stable_desktop_carrier",
    file: ".github/workflows/build-manual.yml",
    required: [
      "workflow_call:",
      "stable_release_set_build",
      "resolve-release-platform-matrix.ts",
      "--policy stable_desktop_additional",
      "--policy manual_all",
      "opl_updater_version:",
      "require_windows_updater_assets:",
      "require_windows_authenticode:",
      "upload_installers_only: true",
      "secrets: inherit",
    ],
    forbidden: [
      "windows_preview_rc",
      "windows-rc-",
      "publish-selected-platforms",
      "environment: release-preview",
      "contents: write",
      "gh release upload",
      "immutable_release_capability_evidence",
      "--clobber",
      "make_latest: true",
      "gh run rerun",
      "gh run cancel",
      "\"repos/$GITHUB_REPOSITORY/immutable-releases\"",
      "inputs.matrix",
      "inputs.command",
      "inputs.os",
    ],
  },
  {
    id: "windows_stable_desktop_reusable_build_gates",
    file: ".github/workflows/_build-reusable.yml",
    required: [
      "require_windows_updater_assets:",
      "require_windows_authenticode:",
      "config.nsis.differentialPackage=true",
      "validate-windows-updater-assets.ts",
      "opl-windows-updater-assets.json",
      "Get-AuthenticodeSignature",
      "TimeStamperCertificate",
      "opl-windows-authenticode-receipt.json",
      "-win-x64.exe.blockmap",
    ],
    forbidden: [
      "config.publish.provider=generic",
      "config.publish.url=",
    ],
  },
  {
    id: "stable_followup_hub",
    file: ".github/workflows/release-stable-post-success-followups.yml",
    required: [
      "name: OPL Stable Follow-ups",
      "workflow_run:",
      "workflow_dispatch:",
      "reconcile_full_addon",
      "reconcile_homebrew_standard",
      "reconcile_homebrew_full",
      "repair_additive",
      "reconcile_desktop_platform",
      "stable-followup-router.ts",
      "uses: ./.github/actions/release-followups/observe",
      "uses: ./.github/actions/release-followups/full-addon",
      "uses: ./.github/actions/release-followups/homebrew-standard",
      "uses: ./.github/actions/release-followups/homebrew-full-handoff",
      "uses: ./.github/workflows/_release-homebrew-full-publish.yml",
      "reconcile-desktop-platforms:",
      "fail-fast: false",
      "desktop_additional_platforms",
      "uses: ./.github/workflows/_release-desktop-platform-addon.yml",
      "source_bundle_digest:",
      "--repair-additive",
      "--expected-old-asset-id",
      "--expected-old-asset-digest",
      "opl-stable-additive-repair-plan-",
      "opl-stable-additive-repair-",
      "opl_app_stable_desktop_followup.v1",
      "platform_reconcile",
      "required_for_standard_or_latest:false",
    ],
    forbidden: [
      "continue-on-error:",
      "dispatch-full:",
      "build-desktop-platforms:",
      "append-desktop-platforms:",
      "seq 1 840",
    ],
  },
  {
    id: "stable_full_addon_lane",
    file: ".github/actions/release-followups/full-addon/action.yml",
    required: [
      "RECONCILE_CONFIRMATION: reconcile_full_addon",
      "opl-release-standard-checkpoint-",
      "opl-release-standard-operation-checkpoint-",
      "standard_built|standard_qualified",
      "stable-release-dispatch.ts",
      "append-full",
      "--execute",
      "published|owner_identified|dispatched",
      ".plan.source.run_id",
      "waits_for_owner_completion:false",
      "opl_app_full_addon_follower.v1",
    ],
    forbidden: [
      "failed_follower_run_id",
      "failed_recovery_run_id",
      "actions/workflows/release-stable.yml/dispatches",
      "prior_ids=",
      "seq 1 60",
      "seq 1 840",
      "gh run rerun",
      "gh run cancel",
    ],
  },
  {
    id: "stable_homebrew_standard_lane",
    file: ".github/actions/release-followups/homebrew-standard/action.yml",
    required: [
      "RECONCILE_CONFIRMATION: reconcile_published_homebrew_standard",
      ".commit.sha current-main.json",
      "opl-release-standard-remote-verify-",
      "opl_homebrew_standard_follower_handoff.v1",
      "same_tag_replacement_allowed: true",
      "core_release_or_latest_blocking: false",
      "--remote-write-mode inspect_only",
      "--remote-write-mode direct_commit",
      "--expected-current-cask-sha256",
      "git -C tap-source push --no-force",
      "core_release_or_latest_blocked:false",
      "second_push_attempted:false",
    ],
    forbidden: [
      "activate-latest",
      "gh release create",
      "gh release upload",
      "gh release edit",
      "for attempt in 1 2 3",
    ],
  },
  {
    id: "stable_homebrew_full_handoff_lane",
    file: ".github/actions/release-followups/homebrew-full-handoff/action.yml",
    required: [
      "RECONCILE_CONFIRMATION: reconcile_published_homebrew_full",
      "opl-release-full-published-${AUTHORITY_RUN_ID}",
      "homebrew-full-handoff.json",
      "opl_homebrew_full_follower_handoff.v1",
      ".source.completed_stage == \"full_qualified\"",
      ".source.checkpoint_transport_executor == \"github_actions\"",
      ".source.transport_run_id",
      ".homebrew_modified == false",
    ],
    forbidden: [
      "git -C tap-source push",
      "OPL_HOMEBREW_TAP_TOKEN",
      "failed_follower_run_id",
      "failed_recovery_run_id",
    ],
  },
  {
    id: "independent_desktop_platform_addon",
    file: ".github/workflows/_release-desktop-platform-addon.yml",
    required: [
      "workflow_call:",
      "build-platform:",
      "append-platform:",
      "uses: ./.github/workflows/build-manual.yml",
      "invocation_mode: stable_release_set_build",
      "platform_policy: stable_desktop_additional",
      "group: opl-release-bundle-global",
      "opl_app_desktop_platform_manifest.v1",
      "append-stable-desktop-assets.ts",
      "--platform-manifest desktop-platform-manifest.json",
      "opl-stable-desktop-append-${{ inputs.source_run_id }}-${{ inputs.platform_id }}",
      "opl_app_stable_desktop_platform_followup.v1",
    ],
    forbidden: [
      "workflow_dispatch:",
      "make_latest: true",
      "gh run rerun",
      "gh run cancel",
      "--clobber",
    ],
  },
  {
    id: "release_bundle_package_scripts",
    file: "package.json",
    required: [
      '"release:framework-adapter": "node --experimental-strip-types scripts/framework-release-adapter.ts"',
      '"release:deadline": "node --experimental-strip-types scripts/release-operation-deadline.ts"',
      '"release:bind-standard": "node --experimental-strip-types scripts/bind-standard-release-track.ts"',
      '"release:historical-candidate-record:status": "node --experimental-strip-types scripts/validate-release-candidate-record.ts --status"',
      '"release:historical-bundle:status": "node --experimental-strip-types scripts/release-bundle.ts status"',
    ],
    forbidden: [
      '"release:stable":',
      '"release:operator":',
      '"release:publish":',
      '"release:bundle":',
      '"release:plan":',
      '"release:cohort-lock":',
      '"release:cohort-plan":',
      '"release:preflight":',
      '"release:closeout":',
      '"release:cleanup-drafts":',
      '"release:gate-reuse-plan":',
      '"release:cohort-manifest":',
      '"release:candidate-record":',
      '"release:candidate-record:resolve-owner":',
      '"release:candidate-record:validate":',
      '"release:candidate-record:status":',
      '"release:owner-candidate-record:verify":',
    ],
  },
  {
    id: "immutable_release_bundle_workflow",
    file: ".github/workflows/_release-bundle.yml",
    required: [
      "workflow_call:",
      "operation:",
      "default: standard",
      "freeze:",
      "standard-build:",
      "seal-standard-identity:",
      "checkpoint-standard:",
      "publish-standard:",
      "opl release freeze",
      "opl release build",
      "opl release checkpoint export",
      "uses: ./.github/workflows/_build-reusable.yml",
      "uses: ./.github/workflows/_release-standard-publish.yml",
      "bind-standard-release-track.ts",
      "standard_identity_sha256",
      "verification_app_ref: ${{ needs.freeze.outputs.app_sha }}",
      "npm --prefix framework-source ci --ignore-scripts",
      "REQUESTED_APP_REF:",
      "App checkout differs from the admitted snapshot.",
      "Shell checkout differs from the admitted snapshot.",
      "Framework checkout differs from the admitted snapshot.",
      "require_macos_gatekeeper: true",
      "secrets: inherit",
    ],
    forbidden: [
      "workflow_dispatch:",
      "broker-admission",
      "--mode lookup",
      "id-token: write",
      "opl release reconcile",
      "environment: release-stable",
      "gh run rerun",
      "gh run cancel",
      "--clobber",
      "verify-release-broker-acceptance.ts",
      "release_attempt_id",
      "release_mutation_payload_sha256",
      "pre_api_admission_receipt_base64",
      "canonical_app_sha=",
      "canonical_shell_sha=",
      "canonical_framework_sha=",
      "standard-qualification:",
      "opl release verify",
    ],
  },
  {
    id: "standard_release_publish_workflow",
    file: ".github/workflows/_release-standard-publish.yml",
    required: [
      "workflow_call:",
      "description: standard or resume_standard",
      "pre-publication-admission:",
      "publish-standard-nonlatest:",
      "remote-digest-verify:",
      "activate-latest:",
      "Verify sealed Standard identity",
      "standard_identity_sha256",
      "opl release publish",
      "opl release reconcile",
      "opl release status",
      "validate-standard-publication-input.ts",
      "stable-operation-publication-record.ts create",
      "publication_record_args=(--publication-record \"$record\")",
      "homebrew-standard-handoff.json",
      "core_release_or_latest_blocking: false",
      "Activate Latest after exact remote parity",
    ],
    forbidden: [
      "workflow_dispatch:",
      "opl release freeze",
      "opl release build",
      "verify-release-broker-acceptance.ts",
      "verify-release-session-lease.ts",
      "gh run rerun",
      "gh run cancel",
      "--clobber",
      "updater-upgrade-qualification:",
      "updater-upgrade-qualification-highest:",
      "homebrew-standard-vm:",
      "publish-homebrew-standard:",
      "homebrew-standard-readback:",
      "OPL_HOMEBREW_TAP_TOKEN",
      "git -C tap-source push",
    ],
  },
  {
    id: "full_release_append_workflow",
    file: ".github/workflows/_release-full-addon.yml",
    required: [
      "workflow_call:",
      "default: append_full",
      "restore-standard:",
      "full-build:",
      "full-qualification:",
      "checkpoint-full:",
      "publish-full:",
      "Append exact Full bytes to the mutable Standard Release",
      "TARGET_STANDARD_RELEASE_TAG: ${{ needs.restore-standard.outputs.target_standard_release_tag }}",
      'standard_tag="$TARGET_STANDARD_RELEASE_TAG"',
      "--pattern opl-release-attestation.json",
      "--standard-attestation \"$standard_attestation\"",
      "opl_app_full_append_boundary_receipt.v1",
      "carrier:{kind:\"same_standard_release_assets\"",
      "full-read-only-reconcile.json",
      "verification_app_ref: ${{ inputs.full_content_app_ref }}",
      "test \"$(jq -r .mutation_attempted full-read-only-reconcile.json)\" = false",
      "standard_updater_metadata_modified:false",
      "latest_modified:false",
    ],
    forbidden: [
      "workflow_dispatch:",
      "uses: ./.github/workflows/opl-updater-upgrade-vm.yml",
      "activate-latest:",
      "Activate Latest",
      "verify-release-broker-acceptance.ts",
      "verify-release-session-lease.ts",
      "gh run rerun",
      "gh run cancel",
      "--clobber",
      "gh release create",
      "adjunct_tag=",
      "--publication-record",
    ],
  },
  {
    id: "stable_release_bundle_entry",
    file: ".github/workflows/release-stable.yml",
    required: [
      "workflow_dispatch:",
      "- standard",
      "- resume_standard",
      "- append_full",
      "uses: ./.github/workflows/_release-bundle.yml",
      "uses: ./.github/workflows/_release-standard-publish.yml",
      "uses: ./.github/workflows/_release-full-addon.yml",
      "channel: stable",
      "protected-operation-admission:",
      "admission:",
      "test \"$GITHUB_RUN_ATTEMPT\" = 1",
      "authority_id:",
      "authority_carrier:",
      "authority_digest:",
      "Reject bare or rerun Stable request before expensive work",
      "stable-operation-control.ts decode-carrier",
      "stable-operation-control.ts verify-authority",
      "stable-operation-control.ts materialize-evidence",
      "stable-operation-control.ts verify-executor",
      "Checkout current Stable workflow executor",
      "Checkout frozen App authority cohort",
      "release-dispatch-guard.ts verify-evidence",
      "release-dispatch-guard.ts preflight",
      "--current-run-id \"$GITHUB_RUN_ID\"",
      "stable-operation-control.ts bind",
      "stable-operation-control.ts verify",
      "Upload immutable operation control evidence",
      "opl-stable-operation-control-${{ github.run_id }}",
      "environment: release-stable",
      "authority_id:",
      "operation_id:",
      "authority_carrier:",
      "authority_digest:",
      "stable-operation-control.ts decode-carrier",
      "stable-operation-control.ts bind",
      "Verify protected Apple credentials in the Stable entry",
      "stable-release-admission-manifest.ts create",
      "actions/runs/$GITHUB_RUN_ID\" --jq .created_at",
      "release-operation-deadline.ts resolve",
      "Upload immutable operation admission",
      "needs: [admission, protected-operation-admission, stable-admission-manifest]",
      "app_ref: ${{ needs.protected-operation-admission.outputs.app_ref }}",
      "shell_ref: ${{ needs.protected-operation-admission.outputs.shell_ref }}",
      "framework_ref: ${{ needs.protected-operation-admission.outputs.framework_ref }}",
      "stable_operation_control_artifact: opl-stable-operation-control-${{ github.run_id }}",
      "stable_operation_control_digest: ${{ needs.protected-operation-admission.outputs.control_digest }}",
      "group: opl-release-bundle-global",
      "cancel-in-progress: false",
    ],
    forbidden: [
      "schedule:",
      "release-broker",
      "verify-release-broker",
      "verify-release-session-lease",
      "release_attempt_id",
      "release_mutation_payload_sha256",
      "pre_api_admission_receipt_base64",
      "packages: write",
      "canonical_app_sha=",
      "canonical_shell_sha=",
      "canonical_framework_sha=",
      "gh release",
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
      "uses: ./.github/workflows/release-source-qualification.yml",
      "source-qualification-receipt.ts",
      "validate-source-qualification-receipt.ts",
    ],
  },
  {
    id: "manual_full_preview_protected_entry",
    file: ".github/workflows/release-manual-full-preview.yml",
    required: [
      "workflow_dispatch:",
      "- publish",
      "- cleanup",
      "handoff_nonce:",
      "handoff_manifest_sha256:",
      "OPL_MANUAL_PREVIEW_INGRESS_ROOT",
      "runs-on: [self-hosted, macOS, ARM64, opl-gui-vm]",
      "environment: release-stable",
      "group: opl-release-bundle-global",
      "cancel-in-progress: false",
      "test \"$GITHUB_RUN_ATTEMPT\" = 1",
      "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a",
      "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c",
      "artifact-ids: ${{ needs.ingress.outputs.artifact_id }}",
      "compression-level: 0",
      "overwrite: false",
      "manual-full-preview-release.ts ingest",
      "manual-full-preview-release.ts verify-artifact",
      "manual-full-preview-release.ts mutate",
      "mutation_retry_performed:false",
    ],
    forbidden: [
      "source_run_id",
      "opl release",
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
      "latest-arm64-mac.yml",
      "update-homebrew",
      "--clobber",
    ],
  },
  {
    id: "manual_full_preview_executor",
    file: "scripts/manual-full-preview-release.ts",
    required: [
      "opl_manual_full_preview_manifest.v1",
      "MANUAL_USABLE_DELIVERED",
      "minimum_host_qa",
      "manual-full-preview-${version}-m1-${sourceLockSha256.slice(0, 12)}",
      "make_latest: 'false'",
      "https://uploads.github.com/repos/${repo}/releases/${releaseId}/assets",
      "artifactDigestRef = `sha256:${input.artifactDigest}`",
      "outcome is unknown after three read-only inspections; mutation was not retried",
      "M2 and Stable append/readback receipts do not bind the same Bundle",
      "exact required formal Stable asset set",
      "deleteRelease",
      "deleteTag",
      "Preview publication changed GitHub Latest",
      "Stable Release ${handoff.stableTag} is not GitHub Latest",
    ],
    forbidden: [
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
      "make_latest: 'true'",
      "--clobber",
      "opl release",
    ],
  },
  {
    id: "nightly_standard_release_entry",
    file: ".github/workflows/release-nightly.yml",
    required: [
      "schedule:",
      "cron: '17 19 * * *'",
      "workflow_dispatch:",
      "operator_confirmation:",
      "publish_nonlatest_nightly",
      "group: opl-standard-nightly",
      "uses: ./.github/workflows/_build-reusable.yml",
      "require_macos_gatekeeper: false",
      "resolve-nightly-release-request.ts",
      "nightly-release-qualification.ts",
      "nightly-release-notes.ts",
      "nightly-notes-baseline.json",
      "nightly-notes-evidence.json",
      "nightly-release-publisher.ts",
      "environment: release-nightly",
    ],
    forbidden: [
      "opl-release-bundle-global",
      "uses: ./.github/workflows/_release-bundle.yml",
      "uses: ./.github/workflows/opl-first-run-vm.yml",
      "require_macos_gatekeeper: true",
      "uses: ./.github/workflows/_release-full-addon.yml",
      "uses: ./.github/workflows/release-webui",
      "make_latest: true",
    ],
  },
  {
    id: "nightly_followup_hub",
    file: ".github/workflows/release-nightly-followups.yml",
    required: [
      "name: OPL Nightly Follow-ups",
      "workflow_run:",
      "workflow_dispatch:",
      "- OPL Standard Nightly Release",
      "reconcile_homebrew",
      "run_sampled_vm",
      "publish-nightly-cask:",
      "environment: release-nightly",
      "OPL_HOMEBREW_TAP_DEPLOY_KEY",
      "git@github.com:${tap_repo}.git",
      "IdentitiesOnly=yes",
      "StrictHostKeyChecking=yes",
      "Casks/one-person-lab-nightly.rb",
      "git -C tap-source push --no-force",
      "retry_performed:false",
      "resolve-sample:",
      "TZ=Asia/Shanghai date +%u",
      "sampled-standard-vm:",
      "uses: ./.github/workflows/opl-first-run-vm.yml",
      "package_profile: standard",
      "require_macos_gatekeeper: false",
    ],
    forbidden: [
      "Casks/one-person-lab-full.rb",
      "make_latest: true",
      "gh workflow run",
      "gh run rerun",
      "OPL_HOMEBREW_TAP_TOKEN",
      "environment: release-stable",
    ],
  },
  {
    id: "webui_operations_hub",
    file: ".github/workflows/release-webui-development.yml",
    required: [
      "name: OPL WebUI Operations",
      "workflow_dispatch:",
      "operation:",
      "- qualify",
      "- publish",
      "- promote",
      "source-authority:",
      "if: ${{ inputs.operation == 'qualify' || inputs.operation == 'publish' }}",
      "webui-carrier:",
      "if: ${{ inputs.operation == 'publish' }}",
      "webui-carrier-qualification:",
      "if: ${{ inputs.operation == 'qualify' }}",
      "promote-webui-latest:",
      "if: ${{ inputs.operation == 'promote' }}",
      "uses: ./.github/workflows/release-webui-stable.yml",
    ],
    forbidden: [
      "stable_authority_run_id:",
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
    ],
  },
  {
    id: "release_bundle_no_mutation_canary",
    file: ".github/workflows/release-bundle-canary.yml",
    required: [
      "permissions:",
      "contents: read",
      "actions: read",
      "schedule:",
      "cron: '0 13 * * *'",
      "workflow_dispatch:",
      "group: opl-release-validation-canary-${{ github.ref }}",
      "cancel-in-progress: true",
      "framework-checkpoint-roundtrip:",
      "contract:",
      "tests/release/release-bundle-workflow-cutover.test.ts",
      "tests/release/release-control-plane-boundary.test.ts",
    ],
    forbidden: [
      "push:",
      "pull_request:",
      "contents: write",
      "secrets:",
      "mode: execute",
      "channel: nightly",
      "opl-release-bundle-global",
      "gh release",
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
      "uses: ./.github/workflows/",
      "packages: write",
    ],
  },
];

const windowsSpecificCheckIds = new Set([
  'docker_webui_clean_windows_dispatch_helper',
  'docker_webui_clean_windows_dispatch_npm_script',
  'docker_webui_clean_windows_runner_bootstrap_runbook',
]);

const windowsSharedCheckIds = new Set([
  'docker_webui_clean_vm_workflow',
]);

export function releaseBoundaryChecksForProfile(
  profile = releaseValidationProfile(),
): ReleaseBoundaryCheck[] {
  if (profile === 'aggregate') return releaseBoundaryChecks;
  if (profile === 'stable') {
    return releaseBoundaryChecks.filter((check) => !windowsSpecificCheckIds.has(check.id));
  }
  return releaseBoundaryChecks.filter((check) =>
    windowsSpecificCheckIds.has(check.id) || windowsSharedCheckIds.has(check.id)
  );
}
