import path from "node:path";
import { fileURLToPath } from "node:url";
import { resolveActiveShellPaths } from "../app-shell-adapter.ts";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const shellPaths = resolveActiveShellPaths();

export type ReleaseBoundaryCheck = {
  id: string;
  file: string;
  required?: string[];
  forbidden?: string[];
  retired?: boolean;
};

export type ReleaseValidationProfile = 'aggregate' | 'stable' | 'windows-preview';

export function releaseValidationProfile(
  value = process.env.OPL_RELEASE_VALIDATION_PROFILE,
): ReleaseValidationProfile {
  if (value === undefined || value === '') return 'aggregate';
  if (value === 'aggregate' || value === 'stable' || value === 'windows-preview') return value;
  throw new Error(`Unsupported OPL_RELEASE_VALIDATION_PROFILE: ${value}.`);
}

export function activeShellReleaseValidationProfile(
  quick: boolean,
  value = process.env.OPL_RELEASE_VALIDATION_PROFILE,
): ReleaseValidationProfile {
  return releaseValidationProfile(
    value === undefined || value === ''
      ? (quick ? 'stable' : 'aggregate')
      : value,
  );
}

export const releaseWorkflowPaths = [
  ".github/workflows/_build-reusable.yml",
  ".github/workflows/_release-bundle.yml",
  ".github/workflows/_release-full-addon.yml",
  ".github/workflows/_release-homebrew-full-publish.yml",
  ".github/workflows/_release-standard-publish.yml",
  ".github/workflows/build-manual.yml",
  ".github/workflows/desktop-release-diagnostics.yml",
  ".github/workflows/docker-webui-clean-linux-vm.yml",
  ".github/workflows/docker-webui-clean-windows-vm.yml",
  ".github/workflows/full-first-install-release.yml",
  ".github/workflows/full-runtime-cache-warmup.yml",
  ".github/workflows/non-release-validation.yml",
  ".github/workflows/opl-first-run-vm.yml",
  ".github/workflows/release-bundle-canary.yml",
  ".github/workflows/release-github-admin-credentials-preflight.yml",
  ".github/workflows/release-manual-full-preview.yml",
  ".github/workflows/release-homebrew-full-follower.yml",
  ".github/workflows/release-nightly.yml",
  ".github/workflows/release-nightly-homebrew-follower.yml",
  ".github/workflows/release-nightly-sampled-vm.yml",
  ".github/workflows/release-stable.yml",
  ".github/workflows/release-stable-optional-existing-base.yml",
  ".github/workflows/release-verify-remote.yml",
];

const windowsPreviewOnlyWorkflowPaths = new Set([
  '.github/workflows/docker-webui-clean-windows-vm.yml',
]);

export function releaseWorkflowPathsForProfile(
  profile = releaseValidationProfile(),
): string[] {
  if (profile === 'aggregate') return releaseWorkflowPaths;
  if (profile === 'stable') {
    return releaseWorkflowPaths.filter((workflowPath) =>
      !windowsPreviewOnlyWorkflowPaths.has(workflowPath)
    );
  }
  return releaseWorkflowPaths.filter((workflowPath) =>
    windowsPreviewOnlyWorkflowPaths.has(workflowPath)
    || workflowPath === '.github/workflows/_build-reusable.yml'
    || workflowPath === '.github/workflows/build-manual.yml'
  );
}

const legacyReleaseBoundaryChecks: ReleaseBoundaryCheck[] = [
  {
    id: "local_first_release_preflight",
    file: "scripts/verify.sh",
    required: [
      "release-preflight)",
      "opl_app_local_release_preflight.v1",
      "actionlint",
      "npm run typecheck",
      "npm run validate:active-shell",
      "npm run test:release-boundary",
      "npm run validate:shell-candidates",
      "npm run build-mac:arm64",
      "github_hosted_required_macos_linux_matrix",
      "github_hosted_optional_platform_matrix_nonblocking",
      "protected_signing_and_notarization_credentials",
      "owner_authoritative_remote_readback",
      "post_publication_clean_machine_certification",
      "public_mutation_allowed: false",
    ],
    forbidden: [
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
      "gh release create",
    ],
  },
  {
    id: "optional_certification_receipt_contract",
    file: "contracts/app-optional-certification-receipt.schema.json",
    required: [
      "opl_app_optional_certification_receipt.v1",
      "\"passed\"",
      "\"failed\"",
      "\"not_run\"",
      "\"unavailable\"",
      "\"required_for_publication\"",
      "\"component_manifest_resigned\"",
    ],
  },
  {
    id: "optional_certification_receipt_validator",
    file: "scripts/validate-optional-certification-receipt.ts",
    required: [
      "passed",
      "failed",
      "not_run",
      "unavailable",
      "certification must never rebuild the artifact",
      "certification must not mutate the component manifest",
      "queued, runner inventory, authentication, or network state cannot prove unavailable",
    ],
  },
  {
    id: "retired_build_and_release_workflow_absent",
    file: ".github/workflows/build-and-release.yml",
    retired: true,
  },
  {
    id: "retired_homebrew_tap_writer_absent",
    file: ".github/workflows/homebrew-tap-update.yml",
    retired: true,
  },
  {
    id: "retired_standalone_webui_stable_writer_absent",
    file: ".github/workflows/webui-ghcr-release.yml",
    retired: true,
  },
  {
    id: "retired_standalone_webui_publish_helper_absent",
    file: "scripts/webui-ghcr-release-step.sh",
    retired: true,
  },
  {
    id: "native_webui_additive_carrier",
    file: ".github/workflows/_release-native-webui-carrier.yml",
    required: [
      "mode:",
      "target_platform:",
      "target_architecture:",
      "OPL_WEBUI_IMAGE_PROFILE: webui-full",
      "NODE_OPTIONS: '--max-old-space-size=8192'",
      "restore-release-checkpoint",
      "standard_identity_sha256",
      "native_webui_follower",
      "infer-standard",
      "opl release operation admit",
      "release-native-webui-carrier.ts publish",
      "release-native-webui-carrier.ts readback",
      "publication-scope external_target",
      "prior_mutation_attempt_id",
      "latest_modified",
      "container_registry_modified",
      "homebrew_modified",
    ],
    forbidden: [
      "packages: write",
      "make_latest",
      "github-activate-latest",
      "docker push",
      "--clobber",
    ],
  },
  {
    id: "webui_stable_follower_recovery",
    file: ".github/workflows/release-webui-follower.yml",
    required: [
      "workflow_run:",
      "OPL Stable Release Bundle",
      "workflow_dispatch:",
      "recover_exact_failed_webui_follower_v9",
      "failed_recovery_v8_run_id",
      "failed-recovery-v3-jobs.json",
      "failed-recovery-v3-artifacts.json",
      "failed-recovery-v4-jobs.json",
      "failed-recovery-v4-artifacts.json",
      "failed-recovery-v5-jobs.json",
      "failed-recovery-v5-artifacts.json",
      "failed-recovery-v6-jobs.json",
      "failed-recovery-v6-artifacts.json",
      "failed-recovery-v7-artifacts.json",
      "failed-recovery-v8-artifacts.json",
      "webui-sidecar-reconcile-26.8.4-",
      "sha256:44eb5268eeb16ca2362d46515da59c3db6ae5537fd9bd69ec42b6845618eed23",
      "Error: absolute file path detected.",
      "fatal: Not a valid commit name 95640c74e0b14ba2e88056de725c417fd1693cf1",
      "FAILED_RECOVERY_V4_RUN_ID: unbound variable",
      "configured_codex_plugin_carrier_owner_descriptor_missing",
      "e9a5cc46766215e4e301d8a59fcaeffc2e00de7a",
      "acdf7738832dcdf569ecea9b63fcbc7d0d47d238",
      "const marker = /\"message\"\\s*:\\s*\"/g",
      "contract_shape_invalid",
      "configured_codex_plugin_carrier_target_currentness_mismatch",
      "runs?event=workflow_dispatch&per_page=100",
    ],
    forbidden: [
      "cancel-in-progress: true",
      "gh run rerun",
      "gh workflow run release-stable.yml",
    ],
  },
  {
    id: "native_webui_additive_follower",
    file: ".github/workflows/release-native-webui-follower.yml",
    required: [
      "workflow_run:",
      "OPL Stable Release Bundle",
      "webui-follower-handoff.json",
      "opl_app_webui_follower_handoff.v1",
      "source.artifact_run_id",
      "source.checkpoint_artifact",
      "source.standard_identity_sha256",
      "target_platform: linux",
      "target_architecture: x86_64",
      "target_platform: darwin",
      "target_architecture: arm64",
      "workflow_dispatch:",
      "recover_exact_failed_native_webui_follower_v1",
      "recover_exact_failed_native_webui_follower_v2",
      "recover_exact_failed_native_webui_follower_v3",
      "failed_recovery_run_id",
      "failed_recovery_v2_run_id",
      "full_authority_run_id",
      "failed-follower-jobs.json",
      "failed-recovery-jobs.json",
      "line 18: rg: command not found",
      "allow_same_tag_full_assets",
      "runs?event=workflow_dispatch&per_page=100",
    ],
    forbidden: [
      "packages: write",
      "publication_artifact_name",
    ],
  },
  {
    id: "native_webui_additive_carrier_script",
    file: "scripts/release-native-webui-carrier.ts",
    required: [
      "planNativeWebuiAssetPublication",
      "publishNativeWebuiAssets",
      "readbackNativeWebuiAssets",
      "Unsupported Native WebUI target",
      "already exists with different bytes",
      "persist_framework_marker_then_exact_read_only_reconcile_no_upload_retry",
      "authenticated_readback",
      "anonymous_readback",
      "latest_modified: false",
      "container_registry_modified: false",
      "homebrew_modified: false",
    ],
    forbidden: [
      "--clobber",
      "make_latest",
      "docker push",
    ],
  },
  {
    id: "framework_release_promotion_helper",
    file: "scripts/framework-release-promotion-step.sh",
    required: [
      "opl-release-promotion-receipt-${OPL_PROMOTION_REQUEST_ID}-${target}",
      "The isolated mutation broker has not produced Framework",
      "gh run download",
      "must contain exactly one JSON receipt",
      "validate-framework-release-promotion-receipt.ts",
    ],
    forbidden: ["gh workflow run", "gh run watch", "run rerun"],
  },
  {
    id: "framework_release_promotion_receipt_validator",
    file: "scripts/validate-framework-release-promotion-receipt.ts",
    required: [
      "opl_release_set_promotion_receipt.v1",
      "promotion_target",
      "carrier.digest",
      "framework_run",
      "framework-source-commit",
      "components.base.source_commit does not match the frozen Framework cohort SHA",
      "components.packages",
      "anonymous_readback.verified_refs",
      "one-person-lab-packages/${packageId}",
    ],
  },
  {
    id: "release_contract_repo",
    file: "contracts/app-release-channel.json",
    required: [
      '"release_repo": "gaofeng21cn/one-person-lab-app"',
      '"source_freeze_currentness_policy"',
      '"remote_and_current_authority_read_mode": "single_cutoff_read"',
      '"canonical_live_catalog_equality_is_prebuild_precondition": false',
      '"host_installed_or_effective_state_is_prebuild_precondition": false',
      '"module_main_or_tag_advancement_triggers_rebuild": false',
      '"explicit security revocation bound to the frozen ref or digest"',
    ],
    forbidden: ['"release_repo": "gaofeng21cn/one-person-lab"'],
  },
  {
    id: "release_cohort_plan_uses_canonical_dry_run_controller",
    file: "scripts/plan-release-cohort.ts",
    required: [
      "'npm run release:stable -- start'",
      "action: 'plan_stable_release_start'",
      "same-cohort non-blocking add-on intent",
    ],
    forbidden: [
      "gh workflow run \"OPL Desktop Release\"",
      "stable_complete requires --include-full-package true",
      "--execute",
    ],
  },
  {
    id: "publish_script_repo",
    file: "scripts/publish-release.ts",
    required: [
      "'gaofeng21cn/one-person-lab-app'",
      "assertRemoteReleaseIsMutableDraft(repo, tag);",
      "run('gh', buildUploadArgs(repo, tag, artifactPath, options.clobber)",
      "already published ${channel} release and is immutable",
      "OPL_RELEASE_MUTATION_STATE_JSON is a test-only fixture and cannot replace remote draft readback.",
      "opl_app_release_publish_recovery_receipt.v1",
      "read_back_then_resume_same_draft_same_cohort",
      "independent_isolated_release_mutation_broker_only",
    ],
    forbidden: ["'gaofeng21cn/one-person-lab'", "['release', 'delete'", "'--cleanup-tag'"],
  },
  {
    id: "update_bridge_repo",
    file: path.relative(
      appRoot,
      path.join(shellPaths.shellRoot, "packages/desktop/src/process/bridge/updateBridge.ts"),
    ),
    required: ["'gaofeng21cn/one-person-lab-app'"],
    forbidden: ["const DEFAULT_REPO = 'gaofeng21cn/one-person-lab'"],
  },
  {
    id: "application_bridge_repo",
    file: path.relative(
      appRoot,
      path.join(
        shellPaths.shellRoot,
        "packages/desktop/src/process/bridge/applicationBridgeCore.ts",
      ),
    ),
    required: ["'gaofeng21cn/one-person-lab-app'"],
    forbidden: ["|| 'gaofeng21cn/one-person-lab'"],
  },
  {
    id: "first_run_vm_download_repo",
    file: ".github/workflows/opl-first-run-vm.yml",
    required: [
      '--repo "$GITHUB_REPOSITORY"',
      "One-Person-Lab-Full-*-mac-arm64.dmg",
      "One-Person-Lab-*-mac-arm64.dmg",
      "release_artifact_name:",
      "release_artifact_run_id:",
      "artifact_app_ref:",
      "smoke_harness_ref:",
      "framework_ref:",
      "framework_sha: ${{ steps.framework_ref.outputs.framework_sha }}",
      "Validate Framework ref before VM runner work",
      "ref: ${{ needs.validate-vm-inputs.outputs.smoke_harness_sha }}",
      "ref: ${{ needs.validate-vm-inputs.outputs.framework_sha }}",
      '--app-sha "${{ needs.validate-vm-inputs.outputs.artifact_app_sha }}"',
      '--shell-sha "${{ needs.validate-vm-inputs.outputs.shell_sha }}"',
      '--verification-app-sha "$GITHUB_SHA"',
      '--verification-shell-sha "${{ needs.validate-vm-inputs.outputs.smoke_harness_sha }}"',
      'scripts/qualification-harness-scope.ts',
      '--verification-scope-proof-base64',
      "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c",
      "run-id: ${{ inputs.release_artifact_run_id || github.run_id }}",
      "Using same-run workflow artifact",
      "Using source workflow run artifact",
      "Checkout OPL Framework bootstrap source",
      "repository: gaofeng21cn/one-person-lab",
      "Prepare OPL Framework bootstrap archive",
      "git -C one-person-lab archive --format=tar.gz --prefix=one-person-lab/",
      'CMD+=(--framework-source-archive "${{ steps.framework_source.outputs.archive_path }}")',
      'CMD+=(--framework-install-script "${{ steps.framework_source.outputs.install_script_path }}")',
      "fetch_release_metadata_with_retry()",
      "Release metadata fetch failed on attempt $attempt",
      "download_asset_with_retry()",
      "download_release_with_retry()",
      "Resolved release DMG asset: $asset_name",
      "Release DMG asset download failed on attempt $attempt",
      "asset.apiUrl || asset.url",
      "Accept: application/octet-stream",
      "Authorization: Bearer ${GH_TOKEN}",
      "curl_args=(-fL --retry 5 --retry-all-errors --retry-delay 10 --connect-timeout 30 --max-time 1800 --continue-at -)",
      "fetch-depth: 1",
      "sparse-checkout: |",
      "/scripts/",
      "/package.json",
      "/bun.lock",
      "/patches/",
      "/packages/*/package.json",
      "sparse-checkout-cone-mode: false",
      "package_profile:",
      "diagnostic_scope:",
      "diagnostic_scope != 'bootstrap_only'",
      "Resolve package profile",
      "--smoke-profile no-clt-clean-vm",
      "--display 1920x1080px",
      "--settings-smoke",
      "--assistant-route-smoke",
      "--codex-functional-check",
      "--codex-ai-self-check",
      '--runtime-profile "${{ steps.package_profile.outputs.runtime_profile }}"',
      "guide_screenshots:",
      "CMD+=(--guide-screenshots)",
    ],
    forbidden: [
      "--repo gaofeng21cn/one-person-lab",
      '--app-sha "$GITHUB_SHA"',
      "ref: ${{ needs.validate-vm-inputs.outputs.shell_sha }}",
      "'/packages/*/package.json'",
      "Materialize active shell dependency metadata",
      "git -C shells/aionui sparse-checkout set",
    ],
  },
  {
    id: "full_release_workflow_uses_app_scripts",
    file: ".github/workflows/full-first-install-release.yml",
    required: [
      "npm --silent run release:full",
      "npm run release:publish",
      "Verify Full signing and notarization credentials",
      "Production Full assets require Developer ID signing and Apple notarization; local authorization fallback is forbidden.",
      "contracts/app-full-third-party-source-manifest.json",
      "contracts/app-release-qualification-input-manifest.json",
      "Resolve default Full build inputs",
      "darwin_arm64_archive_sha256",
      "OPL_FULL_BUN_BIN=$(command -v bun)",
      "OPL_FULL_INCLUDE_BUN_RUNTIME",
      "OPL_FULL_TEMPORAL_CLI_BIN=$(command -v temporal)",
      "Checkout OPL Flow",
      "repository: gaofeng21cn/opl-flow",
      "Validate Full source roots",
      "Required Full source is missing:",
      "OPL_FULL_OPL_FLOW_REF=$(git -C opl-flow rev-parse HEAD)",
      'export OPL_FULL_OPL_FLOW_ROOT="$GITHUB_WORKSPACE/opl-flow"',
      'export OPL_FULL_BUN_BIN="${OPL_FULL_BUN_BIN:-$(command -v bun)}"',
      'export OPL_FULL_TEMPORAL_CLI_BIN="${OPL_FULL_TEMPORAL_CLI_BIN:-$(command -v temporal)}"',
      "Finalize Full Developer ID signing and notarization",
      "scripts/notarize-macos-dmg.ts",
      "full-apple-notarization-receipt.json",
      "full-gatekeeper-launch-policy.json",
      "full-local-authorization-policy.json",
      "full-runtime-currentness-probe.json",
      "full-runtime-native-trust.json",
      '--expected-team-id "$EXPECTED_TEAM_ID"',
      "local-authorization-policy.ts",
      'mounted_app_paths=()',
      'Full first-install DMG must contain exactly one One Person Lab.app',
      'codesign --verify --deep --strict --verbose=2 "$mounted_app_path"',
      '--app-path "$mounted_app_path"',
      'spctl --assess --type execute --verbose=4 "$mounted_app_path"',
      'xcrun stapler validate "$dmg_path"',
      "Upload Full DMG-only workflow artifact",
      "opl-full-first-install-dmg-${{ env.OPL_RELEASE_VERSION }}-mac-arm64",
      "One-Person-Lab-Full-${{ env.OPL_RELEASE_VERSION }}-mac-arm64.dmg",
      "Write Full build artifact cohort manifest",
      "write-build-artifact-cohort.ts",
      "full-intel-finalizer:",
      "runs-on: macos-15-intel",
      "opl-full-intel-finalizer-input-",
      "opl_full_intel_finalizer_handoff_receipt.v1",
      'and .timestamp_signing.authority_endpoint == "system_default"',
      "--kind full",
      '--actions-run-id "$GITHUB_RUN_ID"',
      "Upload Full build artifact cohort manifest",
      "opl-full-first-install-dmg-${{ env.OPL_RELEASE_VERSION }}-mac-arm64-cohort",
      "id: full_package_build",
      "success() && steps.full_package_build.outcome == 'success'",
      'npm run release:version:validate -- --channel stable --version "$OPL_RELEASE_VERSION"',
    ],
    forbidden: [
      "npm run gui:release",
      "packages:full-release",
      "repository: gaofeng21cn/one-person-lab-app",
      "models: read",
      "OPL_RELEASE_NOTES_GITHUB_MODEL",
      "release_mutation_owned_by_caller",
      "OPL_RELEASE_EXISTS: ${{ inputs.publish_to_release",
      "publish_to_release:",
      "npm view @openai/codex version",
      "bundled-full-runtime-package-catalog.json",
      "--framework-bundled-catalog",
    ],
  },
  {
    id: "full_dmg_notarizer_uses_system_default_timestamp",
    file: "scripts/notarize-macos-dmg.ts",
    required: [
      "const timestampAuthoritySelection = 'system_default'",
      "['--force', '--timestamp', '--sign', identity, probePath]",
      "['--force', '--timestamp', '--sign', identity, candidateDmg]",
    ],
    forbidden: [
      "timestamp.apple.com",
      "--timestamp=",
    ],
  },
  {
    id: "desktop_release_workflow_uses_app_scripts",
    file: ".github/workflows/desktop-release.yml",
    required: [
      "release-preflight:",
      "name: Release preflight",
      "release_intent:",
      "release_operator_plan_ref:",
      "gate_reuse_plan_ref:",
      '--release-intent "$RELEASE_INTENT"',
      '--release-operator-plan-ref "$RELEASE_OPERATOR_PLAN_REF"',
      '--gate-reuse-plan-ref "$GATE_REUSE_PLAN_REF"',
      "Generate release:gate-reuse-plan for the same cohort",
      "Monitor: controller uses a bounded absolute watch deadline and read-only reconcile; never start a second watcher.",
      "npm run release:preflight --",
      "release-preflight-summary.json",
      "release-preflight-summary.md",
      "release-workflow-contract:",
      "name: Release workflow contract",
      "name: Checkout OPL Flow policy source",
      "repository: gaofeng21cn/opl-flow",
      "ref: ${{ needs.release-source-gate.outputs.opl_flow_sha }}",
      "path: opl-flow",
      "OPL_FLOW_WORKFLOW_POLICY: ${{ github.workspace }}/opl-flow/contracts/workflow-policy.json",
      "OPL_FULL_OPL_FLOW_ROOT: ${{ github.workspace }}/opl-flow",
      "npm run test:release-boundary",
      "release-source-gate:",
      "name: Release source gate",
      "node --experimental-strip-types scripts/validate-release-source-gate.ts",
      '--app-ref "${{ inputs.artifact_app_sha }}"',
      "--shell-ref \"${{ inputs.shell_ref }}\"",
      "--framework-ref \"${{ inputs.framework_ref }}\"",
      "shell_ref must be the exact frozen Shell SHA",
      "framework_ref must be the exact frozen Framework SHA",
      "--require-shell-format true",
      "cancel-in-progress: false",
      "homebrew_tap_update_required",
      "release-source-gate",
      "uses: ./.github/workflows/_build-reusable.yml",
      "require_macos_gatekeeper: false",
      "name: macos-build-arm64",
      "remote-verify-standard:",
      "runs-on: macos-latest",
      "remote-verify-standard:",
      "needs.standard-first-run-vm-smoke-after-standard-only.result == 'success'",
      "remote-verify-full:",
      "node --experimental-strip-types scripts/prepare-release-assets.ts build-artifacts release-assets",
      "node --experimental-strip-types scripts/validate-release.ts release-assets",
      "--standard-artifacts-dir release-assets",
      "default: new_release",
      'npm run release:version:validate -- --channel stable --version "$OPL_RELEASE_VERSION"',
      "Release $tag is already published and immutable; create a new CalVer instead.",
      '--force-with-lease="refs/tags/$tag:$remote_tag_sha"',
      'if [ "$RELEASE_MODE" = "new_release" ] || [ "$RELEASE_MODE" = "draft_candidate" ]; then',
      "npm run verify-remote-release",
      "draft_candidate",
      "uses: ./.github/workflows/full-first-install-release.yml",
      "full-first-install:",
      "needs.standard-build.result == 'success'",
      "uses: ./.github/workflows/opl-first-run-vm.yml",
      "standard-first-run-vm-smoke-after-standard-only:",
      "standard-first-run-vm-smoke-after-full:",
      "standard-vm-smoke-gate-after-full:",
      "Standard VM smoke must pass before Full publish, remote verification, Homebrew, operator evidence, or readiness aggregation can run",
      "framework_ref: ${{ needs.publish-standard.outputs.framework_sha }}",
      "full-first-run-vm-smoke:",
      "needs.full-first-run-vm-smoke.result == 'success'",
      "one-shot-app-installer-smoke:",
      "docker-webui-smoke:",
      "webui-ghcr-publish:",
      "operator-evidence-bundle-validation:",
      "release-evidence-bundle-${{ inputs.opl_version }}",
      "release-readiness-admission:",
      "Release readiness aggregation is blocked by failed, skipped, or missing required gates",
      "repository: gaofeng21cn/one-person-lab",
      "npm ci",
      "node --experimental-strip-types scripts/collect-release-evidence.ts",
      "--action-id developer_supervisor_refresh",
      "--execute-action",
      '--opl-bin "$GITHUB_WORKSPACE/one-person-lab/bin/opl"',
      '--evidence-source-dir "$full_source_dir"',
      '--evidence-source-dir "$standard_source_dir"',
      '--evidence-source-dir "$remote_source_dir"',
      "manifest_args=(",
      "manifest_args+=(--require-conditional docker_webui_clean_vm_evidence)",
      'node --experimental-strip-types scripts/write-release-evidence-manifest.ts "${manifest_args[@]}"',
      "node --experimental-strip-types scripts/validate-release-evidence-bundle.ts",
      "validation_args+=(--require-conditional docker_webui_clean_vm_evidence)",
      "> evidence-validation-summary.json",
      "'operator-evidence-bundle-validation': '${{ needs.operator-evidence-bundle-validation.result }}'",
      "release-readiness-summary:",
      "scripts/summarize-release-readiness.ts",
      "release-readiness-summary.json",
      "shell_ref:",
      "shell_ref: ${{ inputs.shell_ref }}",
      "release_artifact_name: macos-build-arm64-dmg",
      "release_artifact_name: opl-full-first-install-dmg-${{ inputs.opl_version }}-mac-arm64",
      "actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6",
      "subject-path: release-assets/*",
      "subject-path: full-package-artifacts/*",
      "subject-digest: ${{ steps.build_docker_webui.outputs.full_digest }}",
      "subject-digest: ${{ steps.build_docker_webui.outputs.slim_digest }}",
      "create-storage-record: false",
      "package_profile: standard",
      "package_profile: full",
      "release-addon-readiness-summary-${{ inputs.opl_version }}",
      "promotion_saga_deferred:",
      "source_run_mutates_tap: false",
      "OPL_INSTALL_SCRIPT_URL: file://${{ github.workspace }}/one-person-lab/install.sh",
      "./install.sh --with-app --skip-packages",
      '--label "org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}"',
      '--label "org.opencontainers.image.revision=${SHELL_SHA}"',
      "docker build",
      '-t "one-person-lab-webui:${{ inputs.opl_version }}"',
      "--build-arg OPL_WEBUI_IMAGE_PROFILE=webui-slim",
      '-t "one-person-lab-webui:${{ inputs.opl_version }}-slim"',
      'docker run --rm --entrypoint cat "one-person-lab-webui:${{ inputs.opl_version }}"',
      "/opt/opl/image-manifest.json",
      "/opt/opl/seed/metadata.json",
      "node --experimental-strip-types scripts/validate-webui-runtime-image.ts",
      "--expected-profile webui-full",
      "--expected-profile webui-slim",
      "/api/opl-runtime/startup-maintenance",
      "/api/opl-runtime/update-status",
      "/tmp/opl-webui-startup-maintenance.json",
      "/tmp/opl-webui-update-status.json",
      "node --experimental-strip-types scripts/validate-webui-runtime-smoke-receipts.ts",
      "/tmp/opl-webui-runtime-smoke-receipts-validation.json",
      "same_job_after_docker_webui_smoke",
      "repeated_docker_build: false",
      "image_profiles: ['webui-full', 'webui-slim']",
      "Download WebUI GHCR publish summary",
      "Verify WebUI GHCR publish summary",
      'docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin',
      'write_publish_summary "failed" "ghcr_write_package_denied"',
      "ghcr.io/${image_owner}/one-person-lab-webui",
      "required_actions_access_repository: 'gaofeng21cn/one-person-lab-app'",
      "source_repository: 'https://github.com/${GITHUB_REPOSITORY}'",
      '"${ghcr_image}:${{ inputs.opl_version }}"',
      '"${ghcr_image}:${{ inputs.opl_version }}-slim"',
      "tags: ['${{ inputs.opl_version }}', '${{ inputs.opl_version }}-slim']",
    ],
    forbidden: [
      "npm run gui:release",
      "packages:full-release",
      "repository: gaofeng21cn/one-person-lab-app",
      "write_mode: direct_commit",
      "peter-evans/create-pull-request",
      "pull-requests: read",
      "name: release-evidence-${{ inputs.opl_version }}",
      "npm run release:closeout --",
      "npm run release:actions-timing --",
      "release-closeout-${{ inputs.opl_version }}",
      "release-actions-timing-${{ inputs.opl_version }}",
      "stable-homebrew-tap-update:",
      "full-homebrew-tap-update:",
      "homebrew-standard-first-run-vm-smoke:",
      "uses: ./.github/workflows/homebrew-tap-update.yml",
      '"${ghcr_image}:stable"',
      '"${ghcr_image}:latest"',
    ],
  },
  {
    id: "nightly_standard_release_workflow",
    file: ".github/workflows/nightly-standard-release.yml",
    retired: true,
  },
  {
    id: "docker_webui_clean_linux_vm_workflow",
    file: ".github/workflows/docker-webui-clean-linux-vm.yml",
    required: [
      "name: OPL Docker WebUI Clean Linux VM Smoke",
      "workflow_dispatch:",
      "runs-on: ubuntu-latest",
      "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true",
      "ghcr.io/gaofeng21cn/one-person-lab-webui:latest",
      "artifact_name:",
      "docker-webui-clean-linux-vm-evidence",
      "node --experimental-strip-types scripts/docker-webui-smoke-gate.ts",
      "--gate clean_linux_vm",
      "--validate-result docker-webui-clean-linux-vm/docker-webui-smoke-gate-result.json",
      "docker compose -f docker-webui-clean-linux-vm/home/OnePersonLab/compose.yaml down --remove-orphans || true",
      "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a",
    ],
    forbidden: [
      "--gate existing_docker",
      "--gate clean_windows_vm",
      "packages: write",
      "OPENAI_API_KEY",
      "GHCR_TOKEN",
    ],
  },
  {
    id: "docker_webui_clean_windows_vm_workflow",
    file: ".github/workflows/docker-webui-clean-windows-vm.yml",
    required: [
      "name: OPL Docker WebUI Clean Windows VM Smoke",
      "workflow_dispatch:",
      "runner_labels_json:",
      "runner_inventory_json:",
      '["self-hosted","Windows","X64","docker-webui-clean-vm"]',
      "runner-preflight:",
      "runs-on: ubuntu-latest",
      "workflow_dispatch_input",
      "RUNNER_INVENTORY_JSON",
      "repos/${process.env.GITHUB_REPOSITORY}/actions/runners",
      "runner_inventory_unreadable",
      "missing_clean_windows_self_hosted_runner",
      "docker-webui-clean-windows-vm-runner-blocker",
      "needs: runner-preflight",
      "if: ${{ needs.runner-preflight.result == 'success' }}",
      "runs-on: ${{ fromJSON(inputs.runner_labels_json) }}",
      "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true",
      "ghcr.io/gaofeng21cn/one-person-lab-webui:latest",
      "artifact_name:",
      "docker-webui-clean-windows-vm-evidence",
      "powershell -ExecutionPolicy Bypass",
      "-File scripts/install-docker-webui.ps1",
      "-EvidenceDir windows-clean-evidence",
      "-EvidenceArchive windows-clean-evidence.zip",
      "node --experimental-strip-types scripts/docker-webui-smoke-gate.ts",
      "--gate clean_windows_vm",
      "--evidence windows-clean-evidence.zip",
      "--validate-result docker-webui-clean-windows-vm/docker-webui-smoke-gate-result.json",
      "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a",
      "docker compose -f $composePath down --remove-orphans",
    ],
    forbidden: [
      "--gate existing_docker",
      "--gate clean_linux_vm",
      "runs-on: windows-latest",
      "packages: write",
      "OPENAI_API_KEY",
      "GHCR_TOKEN",
    ],
  },
  {
    id: "docker_webui_clean_windows_dispatch_helper",
    file: "scripts/dispatch-docker-webui-clean-windows-smoke.ts",
    required: [
      "opl_docker_webui_clean_windows_dispatch_plan.v1",
      "runner_inventory_json",
      "missing_clean_windows_self_hosted_runner",
      "docker-webui-clean-windows-vm.yml",
      "actions/runners",
      "workflow",
      "run",
      "--execute",
    ],
  },
  {
    id: "docker_webui_clean_windows_dispatch_npm_script",
    file: "package.json",
    required: [
      "smoke:docker-webui:windows-clean-vm:dispatch",
      "scripts/dispatch-docker-webui-clean-windows-smoke.ts",
    ],
  },
  {
    id: "docker_webui_clean_windows_runner_bootstrap_runbook",
    file: "docs/delivery/install/docker-webui-smoke-gates.md",
    required: [
      "Clean Windows Runner Bootstrap",
      "self-hosted",
      "Windows",
      "X64",
      "docker-webui-clean-vm",
      "Docker Desktop",
      "WSL 2",
      "Settings -> Actions -> Runners -> New",
      "Keep the generated registration token out of docs",
      "npm run smoke:docker-webui:windows-clean-vm:dispatch -- --execute --json",
      "docker-webui-clean-windows-vm-evidence",
      "docker_webui_clean_windows_evidence_artifact",
      "docker-webui-clean-windows-vm-runner-blocker",
      "missing_clean_windows_self_hosted_runner",
      "runner_inventory_unreadable",
    ],
    forbidden: [
      "windows-latest runner is acceptable evidence",
      "registration token:",
      "OPENAI_API_KEY",
      "GHCR_TOKEN",
    ],
  },
  {
    id: "release_notes_evidence_first",
    file: "scripts/publish-release.ts",
    required: [
      "OPL_RELEASE_NOTES_MODE",
      "OPL_RELEASE_NOTES_EVIDENCE_OUTPUT",
      "process.env.OPL_RELEASE_NOTES_MODE || 'ai'",
      "buildReleaseNotesDocument",
      "buildAiReleaseNotesDocument",
      "buildReleaseNotesEvidence",
    ],
    forbidden: ["generate_release_notes: true"],
  },
  {
    id: "release_notes_ai_provider_chain",
    file: "scripts/release-notes-ai-writer.ts",
    required: [
      "OPL_RELEASE_NOTES_PROVIDER",
      "openai_compatible",
      "--probe-openai-compatible",
      "OPL_RELEASE_NOTES_AI_TIMEOUT_SECONDS",
      "OPL_RELEASE_NOTES_OPENAI_COMPATIBLE_BASE_URL",
      "OPL_RELEASE_NOTES_OPENAI_COMPATIBLE_API_KEY",
      "OPL_RELEASE_NOTES_CODEX_BASE_URL",
      "OPL_RELEASE_NOTES_CODEX_API_KEY",
      "OPL_RELEASE_NOTES_MODEL",
      "envValue",
      "OpenAI-compatible provider failed",
      "No online OpenAI-compatible release-note provider is configured.",
      "runCodexProvider",
      "validateAiReleaseNotes",
      "self-referential release-note copy",
      "opening paragraph is process-first",
      "missing opening user benefit paragraph before sections",
      "payload lines formatted as blockquotes",
      "developer memo terms before Technical details",
      "payload ref before Technical details",
      "## Technical details",
      "missing user-facing MAS/MAG/RCA role descriptions",
      "missing concrete runtime change detail",
      "## Install Stable",
      "missing Stable install command",
    ],
    forbidden: [],
  },
  {
    id: "release_notes_agent_runtime_evidence",
    file: "scripts/release-notes/payload.ts",
    required: [
      "buildAgentRuntimeChanges",
      "collectComponentChangeSubjects",
      "research automation and study workflow agent",
      "grant-writing and funding workflow agent",
      "visual deliverable, slide, and report graphics agent",
    ],
    forbidden: [],
  },
  {
    id: "release_notes_agent_runtime_output",
    file: "scripts/release-notes.ts",
    required: [
      "agent_runtime_changes",
      "buildAgentRuntimeChanges",
      "install_command",
      "brew install --cask gaofeng21cn/one-person-lab/one-person-lab",
    ],
    forbidden: [],
  },
  {
    id: "homebrew_tap_boundary_script",
    file: "scripts/update-homebrew-tap.ts",
    required: [
      "manifest_required: true",
      "checksum_required: true",
      "nightly_targets_only_for_nightly: true",
      "stable_promotion_from_nightly_allowed: false",
      "full_first_install_allowed: false",
      "full_first_install_allowed: true",
      "standard_updater_visible: false",
      "bundled_full_runtime_payload_allowed: true",
      "homebrew_allowed_software_objects: opl_base,opl_app",
      "opl_packages_lifecycle_owned_by_homebrew: false",
      "opl_packages_lifecycle_owner: one-person-lab",
      "opl_packages_lifecycle_command: opl packages",
      "package_specific_formula_allowed: false",
      "package_specific_cask_allowed: false",
      "forbidden_package_formulae: mas,mag,rca,oma,obf,mas-scholar-skills,opl-flow",
      "forbidden_package_casks: mas,mag,rca,oma,obf,mas-scholar-skills,opl-flow",
      "publishes_or_pushes_remote: false",
      "app_full_first_install",
      "Nightly Homebrew tap updates may only update the Nightly App cask target.",
      "Nightly Homebrew tap updates must use YY.M.D-nightly or YY.M.D-nightly.r1 through .r9.",
      "Stable Homebrew tap updates must use YY.M.D or YY.M.D-r1 through r9.",
      "Full first-install Homebrew cask updates must stay on the stable channel.",
      "Full first-install Homebrew cask updates may only update Casks/one-person-lab-full.rb.",
      "Homebrew tap updates are App cask-only; OPL Packages are Framework-managed, not Homebrew formulae.",
      "must not reference Full first-install payloads",
    ],
    forbidden: ["from 'node:child_process'", "spawnSync(", "execSync(", "execFileSync("],
  },
  {
    id: "homebrew_tap_package_scripts",
    file: "package.json",
    required: [
      '"homebrew:tap:plan": "node --experimental-strip-types scripts/update-homebrew-tap.ts"',
      '"validate:homebrew-tap": "node --experimental-strip-types scripts/update-homebrew-tap.ts --self-check"',
      '"release:nightly-version:resolve": "node --experimental-strip-types scripts/resolve-nightly-version.ts"',
      '"release:actions-timing": "node --experimental-strip-types scripts/summarize-github-actions-timing.ts"',
      '"release:readiness-summary": "node --experimental-strip-types scripts/summarize-release-readiness.ts"',
      '"release:full:prune-audit": "node --experimental-strip-types scripts/audit-full-runtime-prune-policy.ts"',
    ],
    forbidden: [],
  },
  {
    id: "full_runtime_prune_policy_contract",
    file: "contracts/full-runtime-prune-policy.json",
    required: [
      '"schema": "opl_full_runtime_prune_policy.v1"',
      '"id": "full_runtime_offline_first_install_slim_v1"',
      '"source": "Docker build context"',
      '"source": "npm pack dry-run"',
      '"source": "electron-builder application contents"',
      '"runtime_tree"',
      '"production_node_modules"',
      '"node_toolchain_global_packages"',
      '"app_bundle_staging"',
      '"runtime_assertions"',
      '"validation_examples"',
      '"audit_command": "npm run release:full:prune-audit -- --markdown"',
    ],
    forbidden: ["TODO", "TBD", "2c7fad262938fb4295d2bb866f6b955c0aa2361a"],
  },
  {
    id: "full_runtime_prune_policy_audit_script",
    file: "scripts/audit-full-runtime-prune-policy.ts",
    required: [
      "opl_full_runtime_prune_policy_audit.v1",
      "contracts/full-runtime-prune-policy.json",
      "validation_examples",
      "runtime_scan_diff",
      "--runtime-root",
      "--baseline",
      "collectRuntimeAssertions",
    ],
    forbidden: ["TODO", "TBD"],
  },
  {
    id: "release_actions_timing_script",
    file: "scripts/summarize-github-actions-timing.ts",
    required: [
      "opl_github_actions_timing_summary.v1",
      "gh run view",
      "--json",
      "failed_or_cancelled_run_wall_seconds",
      "unaccounted_operator_seconds",
      "top_jobs",
      "top_steps",
    ],
    forbidden: ["gh run watch", "gh run download"],
  },
  {
    id: "release_closeout_script",
    file: "scripts/closeout-release-run.ts",
    required: [
      "opl_release_closeout_summary.v1",
      "Agent orchestration wall time",
      "github_actions_workflow_wall_time",
      "agent_orchestration_wall_time_seconds",
      "downloads_large_artifacts: false",
      "forbiddenLargeArtifactPatterns",
      "workflow_default_release_summary",
      "release-candidate-record-${options.version}",
      "release-readiness-summary-${options.version}",
      "remote-release-verification-${options.version}",
      "validate-release-candidate-record.ts",
      "--promote-ready",
      "owner_needed_release_owner_resolution",
      "release_owner_verdict_ref",
      "release_owner_receipt_ref",
      "release_owner_typed_blocker_ref",
      "gh run view",
      "gh run download",
      "inspect_logs_only_after",
    ],
    forbidden: ["One-Person-Lab-*.dmg", "One-Person-Lab-Full-*.dmg"],
  },
  {
    id: "release_candidate_record_script",
    file: "scripts/write-release-candidate-record.ts",
    required: [
      "opl_app_release_candidate_record_writer_retired.v1",
      "retired_fail_closed",
      "historical_read_only",
      "candidate_record_generated: false",
      "authoritative_for_new_release: false",
      "mutation_authorized: false",
      "framework_opl_release_portable_checkpoint_and_receipt",
      "opl_release_bundle_checkpoint.v1",
      "opl_release_bundle_executor_receipt.v1",
      "opl release status --bundle <sha256:digest> --store <directory>",
      "inspect_framework_checkpoint_and_receipts",
    ],
    forbidden: ["TODO", "TBD", "ready_to_promote", "release:stable -- promote", "--execute"],
  },
  {
    id: "release_gate_reuse_plan_script",
    file: "scripts/plan-release-gate-reuse.ts",
    required: [
      "opl_release_gate_reuse_plan.v1",
      "opl_release_gate_reuse_digest.v1",
      "reuse_plan_can_skip_release_gate_by_itself: false",
      "workflow_must_explicitly_consume_reuse_allowed_decision: true",
      "remote verified asset name/size/sha256 set changed",
      "previous candidate status is",
      "ready_to_promote",
      "current preflight did not resolve shell ref sha",
      "current preflight app commit",
      "does not match requested shell ref",
      "does not match requested framework ref",
      "same version, release mode, inputs, app commit, resolved refs, remote asset digests, and previous passed gate evidence",
      "reuse_digest",
      "cohort",
    ],
    forbidden: ["TODO", "TBD"],
  },
  {
    id: "release_candidate_record_validator_script",
    file: "scripts/validate-release-candidate-record.ts",
    required: [
      "opl_app_historical_release_candidate_inspection.v1",
      "opl_release_candidate_record.v1",
      "ready_to_promote",
      "historical_read_only",
      "authoritative_for_new_release: false",
      "promote_ready: false",
      "mutation_authorized: false",
      "framework_opl_release_portable_checkpoint_and_receipt",
      "opl_release_bundle_checkpoint.v1",
      "opl_release_bundle_executor_receipt.v1",
      "opl release status --bundle <sha256:digest> --store <directory>",
      "inspect_framework_checkpoint_and_receipts",
      "--promote-ready",
      "--status",
    ],
    forbidden: ["TODO", "TBD", "receipt-gated", "release:stable -- promote", "--execute"],
  },
  {
    id: "release_preflight_script",
    file: "scripts/validate-release-preflight.ts",
    required: [
      "opl_release_preflight.v1",
      "release-preflight-summary.json",
      "release-preflight-summary.md",
      "refresh_existing requires GitHub Release",
      "refresh_existing may mutate only an unpublished draft",
      "expected YY.M.D or YY.M.D-r1 through r9",
      "release_target",
      "tap_update_required",
      "desktop_release_promote_after_publish",
      "workflow_preflight_shape",
      "release_plan",
      "release_refs",
      "codex_package_metadata",
      "app-release-qualification-input-manifest.json",
      "@openai/codex@${frozen.version}",
      "frozen.platform.version",
      "homebrew_tap_token",
      "macos_local_authorization",
    ],
    forbidden: ["TODO", "TBD"],
  },
  {
    id: "reusable_build_gatekeeper_policy",
    file: ".github/workflows/_build-reusable.yml",
    required: [
      "macos-signing-preflight:",
      "name: macOS release signing preflight",
      "runs-on: macos-14",
      "Import Developer ID identity and authenticate notarization",
      "scripts/verify-apple-release-credentials.ts",
      "Upload sanitized Apple credential preflight receipt",
      "opl-apple-release-credentials-preflight-${{ github.run_id }}",
      "require_macos_gatekeeper:",
      "OPL_REQUIRE_MACOS_GATEKEEPER",
      "Write macOS Stable local authorization policy",
      "Ensure macOS standard updater ZIP distributable",
      "Finalize Standard Developer ID signing and notarization",
      "Verify Standard final distribution trust",
      'expected_zip="One-Person-Lab-${OPL_RELEASE_VERSION}-mac-${target_arch}.zip"',
      'expected_zip_blockmap="${expected_zip}.blockmap"',
      "Missing standard updater ZIP",
      "Missing standard updater ZIP blockmap",
      "--mac dmg zip",
      '--prepackaged "$app_path"',
      'grep -q "$expected_zip" "$metadata"',
      'spctl --assess --type execute --verbose=4 "$app_path"',
      "standard-local-authorization-policy.json",
      "standard-gatekeeper-launch-policy.json",
      "standard-apple-notarization-receipt.json",
      "scripts/notarize-macos-dmg.ts",
      "scripts/update-electron-updater-metadata.ts",
      "--package-kind app_standard",
    ],
    forbidden: [
      "opl_flow_ref:",
      "name: Checkout OPL Flow policy source",
      "repository: gaofeng21cn/opl-flow",
      "OPL_FLOW_WORKFLOW_POLICY",
      "OPL_FULL_OPL_FLOW_ROOT",
    ],
  },
  {
    id: "apple_release_credentials_preflight_script",
    file: "scripts/verify-apple-release-credentials.ts",
    required: [
      "opl_apple_release_credentials_preflight.v1",
      "Apple release credential preflight requires a macOS runner.",
      "create-keychain",
      "set-key-partition-list",
      "find-identity",
      "--timestamp",
      "--options",
      "runtime",
      "TeamIdentifier mismatch",
      "notarytool",
      "history",
      "admission_eligible",
      "first-attempt workflow_dispatch on canonical App main",
      "submission_performed: false",
      "release_dispatch_performed: false",
      "public_asset_write_performed: false",
      "canonical_main_credential_runtime_preflight_not_release_or_artifact_qualification",
      "<redacted>",
    ],
    forbidden: [
      "notarytool submit",
      "release create",
      "release upload",
      "contents: write",
      "packages: write",
    ],
  },
  {
    id: "stable_release_admission_manifest",
    file: "scripts/stable-release-admission-manifest.ts",
    required: [
      "opl_stable_release_admission_manifest.v1",
      "requiredSecretNames",
      "validateReleaseHomebrewDistribution",
      "resolveStableReleaseVersion",
      "assertPromotionTargetIsNewerThanPublishedStable",
      "anonymousWebuiTags",
      "activeReleaseStatuses",
      "parseGitHubJsonLookup",
      "readOwnerWorkflowRuns",
      "raw_standard_version_or_ref_inputs_allowed: false",
      "read_only_reconcile_without_rerun_redispatch_or_cancel",
      "manifest_digest",
    ],
    forbidden: [
      "gh workflow run",
      "gh release create",
      "gh release upload",
      "gh run rerun",
      "gh run cancel",
      "git push",
    ],
  },
  {
    id: "release_dispatch_guard",
    file: "scripts/release-dispatch-guard.ts",
    required: [
      "opl_release_dispatch_guard.v1",
      "['ls-remote'",
      "logical_query_count: 1",
      "tls_handshake_timeout",
      "unexpected_eof",
      "credential_failure",
      "node_structured_json_without_jq",
      "operationStartedAt",
      "mutation_retry_count: 0",
      "read_only_reconcile_only: true",
      "replacement_allowed: false",
      "redispatch_allowed: false",
    ],
    forbidden: [
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
      "gh release",
      "git push",
    ],
  },
  {
    id: "shell_product_profile_consumer_gate",
    file: "scripts/validate-shell-product-profile-consumer.ts",
    required: [
      "opl_shell_product_profile_consumer_gate.v1",
      "temporary_exact_shell_archive",
      "tests/unit/common-config/oplProductProfile.test.ts",
      "syncAppProductProfileToShell",
      "source_shell_mutated: false",
    ],
    forbidden: [
      "gh workflow run",
      "git push",
      "release create",
    ],
  },
  {
    id: "apple_release_credentials_preflight_workflow",
    file: ".github/workflows/release-apple-credentials-preflight.yml",
    required: [
      "name: Release Apple Credentials Preflight",
      "workflow_dispatch:",
      "contents: read",
      "cancel-in-progress: false",
      "large_dmg_canary:",
      "runs-on: macos-15-intel",
      "timeout-minutes: 45",
      "environment: release-stable",
      "ref: ${{ github.sha }}",
      "node-version: '24'",
      "scripts/verify-apple-release-credentials.ts",
      "--large-dmg-canary",
      "Upload sanitized Apple credential preflight receipt",
      "if: ${{ always() }}",
      "Stable admission authority: false",
      "retention-days: 30",
    ],
    forbidden: [
      "contents: write",
      "packages: write",
      "actions: write",
      "gh workflow run",
      "gh release",
      "git push",
      "notarytool submit",
    ],
  },
  {
    id: "github_release_admin_credentials_preflight_workflow",
    file: ".github/workflows/release-github-admin-credentials-preflight.yml",
    required: [
      "name: Release GitHub Admin Credentials Preflight",
      "workflow_dispatch:",
      "contents: read",
      "actions: read",
      "cancel-in-progress: false",
      "runs-on: ubuntu-latest",
      "timeout-minutes: 5",
      "environment: release-stable",
      "persist-credentials: false",
      "scripts/verify-github-release-admin-credential.ts",
      "OPL_GITHUB_RELEASE_ADMIN_TOKEN: ${{ secrets.OPL_GITHUB_RELEASE_ADMIN_TOKEN }}",
      "Upload sanitized GitHub release-admin credential preflight receipt",
      "if: ${{ always() }}",
      "Stable admission authority: false",
      "Release or repository-setting mutation authorized: false",
      "retention-days: 30",
    ],
    forbidden: [
      "contents: write",
      "packages: write",
      "actions: write",
      "--method POST",
      "--method PUT",
      "--method PATCH",
      "--method DELETE",
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
      "gh release",
      "git push",
    ],
  },
  {
    id: "github_release_admin_credentials_preflight_verifier",
    file: "scripts/verify-github-release-admin-credential.ts",
    required: [
      "opl_app_github_release_admin_credential_preflight.v1",
      ".github/workflows/release-github-admin-credentials-preflight.yml",
      "refs/heads/main",
      "workflow_dispatch_required",
      "canonical_main_required",
      "first_attempt_required",
      "github_release_admin_credential_rejected",
      "github_release_admin_credential_scope_rejected",
      "repository_immutability_setting_not_safe",
      "raw_response_persisted: false",
      "raw_error_persisted: false",
      "repository_setting_mutation_authorized: false",
      "release_mutation_authorized: false",
      "dispatch_rerun_cancel_authorized: false",
      "'GET'",
    ],
    forbidden: [
      "'POST'",
      "'PUT'",
      "'PATCH'",
      "'DELETE'",
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
      "gh release",
      "git push",
    ],
  },
  {
    id: "release_asset_local_authorization_verifiers",
    file: "scripts/verify-remote-release-assets.ts",
    required: [
      "opl-release-attestation.json",
      "full-local-authorization-policy.json",
      "full-runtime-currentness-probe.json",
      "full-runtime-native-trust.json",
      "assertStandardDistributionTrust",
      "assertStandardUpdaterAppBundleTrust",
      "standardUpdaterAppBundleTrust",
      "standard_updater_app_bundle_trust",
      "apple_developer_id_required",
      "gatekeeper_required",
      "notarization_receipt_sha256",
      "TeamIdentifier",
      "Signature",
      "Developer ID Application:",
      "assertFullRuntimeNativeTrust",
      "spctl_status",
      "codesign_status",
      "stapler",
    ],
    forbidden: [],
  },
  {
    id: "first_run_vm_local_authorization_policy",
    file: path.relative(
      appRoot,
      path.join(shellPaths.shellRoot, "scripts/opl-first-run-vm-smoke.mjs"),
    ),
    required: [
      "xattr', ['-dr', 'com.apple.quarantine', targetApp]",
      "gatekeeper-launch-policy.json",
      "gatekeeper_required: gatekeeperRequired",
      "quarantine_removal_required: !gatekeeperRequired",
      "const homebrewFullCask = installOrigin === 'homebrew_full_cask'",
      "const gatekeeperRequired = hooks.requireGatekeeper === true || homebrewFullCask",
      "quarantine_mutation_performed: gatekeeperRequired ? false : null",
      "local_authorization_status: localAuthorizationStatus",
      "'rejected_allowed_unsigned'",
      "'failed_allowed_unsigned'",
      "(hooks.countQuarantineAttributes ?? countQuarantineAttributes)(appPath)",
      "hooks.countQuarantineAttributes ?? countQuarantineAttributes",
      "quarantine_attribute_count: quarantineAttributeCount",
      "if (!gatekeeperRequired && quarantineAttributeCount !== 0)",
      "if (gatekeeperRequired && spctl.status !== 0)",
      "Production App failed the blocking Gatekeeper assessment before first launch.",
      "if (!options.requireGatekeeper)",
    ],
    forbidden: [
      "if (codesign.status !== 0)",
      "if (codesign.status !== 0 || spctl.status !== 0)",
      "Gatekeeper launch policy rejected the packaged app before first launch.",
    ],
  },
  {
    id: "first_run_vm_runtime_refresh_production_evidence",
    file: path.relative(
      appRoot,
      path.join(shellPaths.shellRoot, "scripts/opl-first-run-vm-smoke.mjs"),
    ),
    required: [
      "function buildRuntimeRefreshProbePlan(requestedHash, timeoutMs = DEFAULT_RUNTIME_REFRESH_TIMEOUT_MS)",
      "requestedHash === '#/settings/runtime'",
      "mode: 'settings-maintenance-updates'",
      "aliasResolvedHash: '#/settings/environment'",
      "refreshHash: '#/settings/environment?section=updates'",
      "function settingsRuntimeAliasResolutionExpression(requestedHash, aliasResolvedHash)",
      "function settingsMaintenanceUpdatesReadinessExpression(refreshHash)",
      "function settingsUpdatesRefreshButtonIdleExpression()",
      "function settingsUpdatesRefreshClickExpression()",
      "const selector = '[data-testid=\"opl-managed-update-refresh\"]'",
      "requestedHash === '#/runtime'",
      "mode: 'runtime-v2'",
      "resolvedHashPrefixes: ['#/runtime']",
      "async function exerciseRuntimeRefresh(client, targetHash, timeoutMs = DEFAULT_RUNTIME_REFRESH_TIMEOUT_MS)",
      "settingsRuntimeAliasResolutionExpression(probePlan.requestedHash, probePlan.aliasResolvedHash)",
      "settingsMaintenanceUpdatesReadinessExpression(probePlan.refreshHash)",
      "settingsUpdatesRefreshClickExpression()",
      "requested_hash: targetHash",
      "alias_resolved_hash: aliasResolution.aliasResolvedHash ?? aliasResolution.hash",
      "resolved_hash: resolvedHash",
      "const runtimeRefreshTimeoutMs = Math.min(",
      "options.codexReadinessPhaseTimeoutMs ?? options.timeoutMs",
      "const settingsRuntimeRefresh = await (hooks.exerciseRuntimeRefresh ?? exerciseRuntimeRefresh)(",
      "'#/settings/runtime',",
      "id: 'runtime-settings-alias'",
      "const standaloneRuntimeRefresh = await (hooks.exerciseRuntimeRefresh ?? exerciseRuntimeRefresh)(",
      "'#/runtime',",
      "id: 'runtime-status'",
    ],
    forbidden: [],
  },
  {
    id: "first_run_vm_profile_aware_assistant_smoke",
    file: path.relative(
      appRoot,
      path.join(shellPaths.shellRoot, "scripts/opl-first-run-vm-smoke.mjs"),
    ),
    required: [
      "homeAssistantStandardLaunchGateExpression",
      "homeAssistantWorkspaceContextExpression",
      "homeAssistantRouteSendWithoutActivationExpression",
      "frameworkStageRuntimeActivationExpression",
      "activeConversationRouteReceiptExpression",
      "data-opl-workspace-selected",
      "data-opl-workspace-path",
      "options.runtimeProfile !== 'full'",
      "verification_mode: 'launch_gate'",
      "verification_mode: 'route_receipt'",
      "workspace_guid_ui_send_without_shell_activation_then_conversation_get",
      "home-starter-${id}",
      "assistant_launch_gates_checked",
      "not_applicable_standard",
    ],
    forbidden: [
      "createAssistantRouteReceiptConversationExpression",
      "POST /api/conversations",
    ],
  },
  {
    id: "one_shot_unsigned_local_authorization",
    file: "install.sh",
    required: [
      "--stable-macos-install",
      "STABLE_MACOS_PACKAGE_PROFILE=${OPL_STABLE_MACOS_PACKAGE_PROFILE:-full}",
      "resolve_latest_release_tag()",
      "release_asset_name()",
      "download_or_use_dmg()",
      "download_and_validate_component_manifest()",
      "Release quality: Preview (Dev)",
      "Release quality: Preview (Nightly)",
      "Release quality: not asserted for a custom DMG source.",
      "Component manifest does not bind one exact Standard DMG artifact",
      "Latest pointer selects this exact release but does not change its declared quality.",
      "copy_app_from_dmg()",
      "Mounted DMG must contain exactly one App bundle",
      "stable_macos_install()",
      "Stable macOS App install is currently supported only on macOS arm64.",
      "hdiutil attach -nobrowse -readonly",
      'ditto "$source_app" "$OPL_LOCAL_APP_PATH"',
      "run_with_sudo_fallback",
      "--authorize-local-app-only",
      "--authorize-local-app",
      "--app-path",
      "OPL_LOCAL_APP_PATH=${OPL_LOCAL_APP_PATH:-/Applications/One Person Lab.app}",
      'Type "authorize" to continue',
      'xattr -dr com.apple.quarantine "$OPL_LOCAL_APP_PATH"',
      'codesign --verify --deep --strict --verbose=2 "$OPL_LOCAL_APP_PATH"',
      'spctl --assess --type execute --verbose=4 "$OPL_LOCAL_APP_PATH"',
      "quarantine_before",
      "quarantine_after",
      "One Person Lab macOS App install finished.",
    ],
    forbidden: [],
  },
  {
    id: "install_exposure_unsigned_and_temporal_policy",
    file: "contracts/app-install-exposure-policy.json",
    required: [
      '"surface": "stable_local_authorized_macos_install"',
      '"entrypoint": "install.sh --stable-macos-install --yes"',
      '"compatibility_entrypoints": []',
      '"retired_entrypoints"',
      '"compatibility_wrapper_status": "retired"',
      '"install-stable.sh"',
      '"release_quality_source": "exact_component_manifest"',
      '"latest_pointer_is_quality_independent": true',
      '"non_stable_disclosure_before_target_mutation": true',
      '"legacy_component_manifest_policy": "allow_only_published_non_prerelease_pre_v3_manifest_with_quality_unasserted_disclosure"',
      '"default_package_profile": "full"',
      '"hdiutil attach -nobrowse -readonly"',
      '"ditto"',
      '"open"',
      '"surface": "unsigned_local_app_authorization"',
      '"entrypoint": "install.sh --authorize-local-app-only"',
      '"xattr -dr com.apple.quarantine"',
      '"codesign --verify --deep --strict --verbose=2"',
      '"spctl --assess --type execute --verbose=4"',
      '"auto_configuration_entrypoints"',
      '"opl system startup-maintenance"',
      '"must_export_local_defaults_before_provider_checks": true',
      '"must_surface_service_worker_and_dependency_diagnostics": true',
      '"must_not_block_ready_to_launch_on_worker_residency": true',
      '"must_fail_closed_when_packaged_temporal_payload_is_missing": true',
    ],
    forbidden: [],
  },
  {
    id: "desktop_release_evidence_notes",
    file: ".github/workflows/desktop-release.yml",
    required: [
      "GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
      "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
      "prepare-standard-release-notes:",
      "prepare-full-release-notes:",
      "OPL_RELEASE_NOTES_MODE: template",
      "--input standard-release-notes-template.md",
      "--input full-release-notes-template.md",
      "OPL_RELEASE_NOTES_FILE: prepared-standard-release-notes/standard-release-notes.md",
      "OPL_RELEASE_NOTES_FILE: prepared-full-release-notes/full-release-notes.md",
      '--release-notes-file "$OPL_RELEASE_NOTES_FILE"',
      "prepared-standard-release-notes-${{ inputs.opl_version }}",
      "prepared-full-release-notes-${{ inputs.opl_version }}",
    ],
    forbidden: [
      "Install Codex release-note writer",
      "Configure Codex release-note writer",
      "scripts/setup-release-notes-codex-config.ts",
      "models: read",
      "OPL_RELEASE_NOTES_GITHUB_MODEL",
    ],
  },
  {
    id: "remote_release_verification_workflow_uses_app_script",
    file: ".github/workflows/release-verify-remote.yml",
    required: ["runs-on: macos-latest", "npm run verify-remote-release", "--include-full-package"],
    forbidden: [
      "npm run gui:release",
      "packages:full-release",
      "repository: gaofeng21cn/one-person-lab-app",
    ],
  },
  {
    id: "non_release_validation_workflow",
    file: ".github/workflows/non-release-validation.yml",
    required: [
      "name: OPL Non-Release Validation",
      "push:",
      "branches:",
      "- main",
      "paths:",
      "- '.github/actions/**'",
      "- '.github/workflows/**'",
      "- 'contracts/**'",
      "- 'install.sh'",
      "- 'package.json'",
      "- 'package-lock.json'",
      "- 'scripts/**'",
      "- 'tests/release/**'",
      "- 'tsconfig.json'",
      "workflow_dispatch:",
      "permissions:",
      "contents: read",
      "name: App release-boundary tests",
      "runs-on: ubuntu-latest",
      "actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10",
      "uses: ./.github/actions/setup-active-shell-deps",
      "install-dependencies: 'true'",
      "name: Checkout OPL Flow policy source",
      "ref: 2c7fad262938fb4295d2bb866f6b955c0aa2361a",
      "OPL_FLOW_WORKFLOW_POLICY: ${{ github.workspace }}/opl-flow/contracts/workflow-policy.json",
      "OPL_FULL_OPL_FLOW_ROOT: ${{ github.workspace }}/opl-flow",
      "tests/release/windows-preview-bits-powershell.test.ts",
      "npm run test:release-boundary",
      "npm run validate:release-boundary",
    ],
    forbidden: [
      "contents: write",
      "packages: write",
      "actions: write",
      "gh release",
      "npm run release:publish",
      "npm run release:full",
      "npm run build",
      "npm run package",
      "uses: ./.github/workflows/_build-reusable.yml",
      "uses: ./.github/workflows/full-first-install-release.yml",
      "uses: ./.github/workflows/desktop-release.yml",
    ],
  },
  {
    id: "windows_updater_package_validation_workflow",
    file: ".github/workflows/windows-updater-package-validation.yml",
    required: [
      "name: Windows Updater Package Validation",
      "workflow_dispatch:",
      "shell_ref:",
      "framework_ref:",
      "permissions:",
      "contents: read",
      "persist-credentials: false",
      "runs-on: windows-2022",
      "Build updater-capable Windows x64 package",
      "config.nsis.differentialPackage=true",
      "validate-windows-updater-assets.ts",
      "One-Person-Lab-${{ inputs.release_version }}-win-x64.exe.blockmap",
      "latest.yml",
      "opl-windows-updater-assets.json",
      "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a",
      "Upload non-published updater validation assets",
    ],
    forbidden: [
      "contents: write",
      "packages: write",
      "actions: write",
      "secrets: inherit",
      "GH_TOKEN",
      "GITHUB_TOKEN",
      "gh release",
      "gh api",
      "make_latest",
      "uses: ./.github/workflows/_build-reusable.yml",
      "Get-AuthenticodeSignature",
      "opl-windows-authenticode-receipt.json",
      "npm run release:publish",
      "config.publish.provider=generic",
      "config.publish.url=",
    ],
  },
  {
    id: "full_runtime_cache_warmup_reuses_full_workflow",
    file: ".github/workflows/full-runtime-cache-warmup.yml",
    required: [
      "uses: ./.github/workflows/full-first-install-release.yml",
      "force_rebuild_runtime_cache:",
    ],
    forbidden: ["npm run gui:release", "packages:full-release", "gh release upload"],
  },
  {
    id: "desktop_release_promote_verifies_before_publish",
    file: ".github/workflows/desktop-release-promote.yml",
    required: [
      "release_run_id:",
      "release-candidate-record.json",
      "npm run release:candidate-record:validate",
      'npm run release:version:validate -- --channel stable --version "${{ inputs.opl_version }}"',
      "stable_session_id:",
      "release_set_generation:",
      "standard_vm_run_id:",
      "Resolve immutable cohort",
      "APP_SHA: ${{ inputs.artifact_app_sha }}",
      "FRAMEWORK_REF: ${{ inputs.framework_ref }}",
      "Rebuild missing owner-resolution evidence from exact qualified source",
      "scripts/write-release-candidate-record.ts",
      "npm run verify-remote-release",
      "Validate exact Standard qualification receipt",
      "Resolve release owner gate from Standard readiness",
      "standard_vm_evidence_base64: ${{ steps.standard-vm.outputs.evidence_base64 }}",
      "evidence_base64=${encoded}",
      "STANDARD_VM_EVIDENCE_BASE64: ${{ needs.prepare.outputs.standard_vm_evidence_base64 }}",
      "Publish release without changing latest",
      "-F draft=false -f make_latest=false",
      "-f make_latest=true",
      'gh release view "$tag"',
      "--json tagName,isDraft,isPrerelease,publishedAt,assets",
      "gh release list",
      "--json tagName,isLatest,isDraft",
      "Validate brokered atomic Standard distribution",
      "Publish and promote exact Framework Release Set",
      "bash scripts/framework-release-promotion-step.sh candidate",
      "bash scripts/framework-release-promotion-step.sh latest-stable",
      "OPL_EXPECTED_CARRIER_DIGEST: ${{ steps.candidate.outputs.carrier_digest }}",
      "OPL_FRAMEWORK_SOURCE_COMMIT: ${{ needs.prepare.outputs.framework_sha }}",
      "Reusing immutable brokered Stable distribution receipt",
      "package_profile: homebrew-standard",
      "Activate App latest after Standard distribution gates",
      "opl-app-promotion-saga-receipt.json",
    ],
    forbidden: [
      "npm run gui:release",
      "packages:full-release",
      "repository: gaofeng21cn/one-person-lab-app",
      "uses: ./.github/workflows/homebrew-tap-update.yml",
      "channel: stable",
      "package_profile: homebrew-full",
      "oras tag",
      "WEBUI_VERSION_DIGEST",
      "needs.stable-homebrew-tap-update.result == 'success' && (!inputs.include_full_package || needs.full-homebrew-tap-update.result == 'success')",
      "gh workflow run desktop-release-full-addon.yml",
      "gh run rerun",
    ],
  },
  {
    id: "desktop_release_cleanup_drafts_workflow",
    file: ".github/workflows/desktop-release-cleanup-drafts.yml",
    required: [
      "name: OPL Desktop Release Cleanup Drafts",
      "workflow_dispatch:",
      "dry_run:",
      "npm run release:cleanup-drafts",
      "--summary-path release-draft-cleanup-summary.json",
      "--request-brokered-execute",
      "--dry-run",
      "if: ${{ always() }}",
      "contents: read",
      "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a",
    ],
    forbidden: [
      "One-Person-Lab-*.dmg",
      "gh release download",
      "actions/download-artifact",
      "contents: write",
      "gh release delete",
      "--cleanup-tag",
      "cleanup_args+=(--execute)",
    ],
  },
  {
    id: "release_draft_cleanup_script_fail_closed",
    file: "scripts/cleanup-draft-release-candidates.ts",
    required: [
      "opl_release_draft_candidate_cleanup.v2",
      "brokered_cleanup_unavailable",
      "independent_isolated_release_mutation_broker",
      "release_draft_cleanup",
      "broker_mutation_available: false",
      "direct_github_release_delete_allowed: false",
      "direct_tag_cleanup_allowed: false",
    ],
    forbidden: [
      "['release', 'delete'",
      "'--cleanup-tag'",
      "'-X', 'DELETE'",
    ],
  },
  {
    id: "desktop_release_diagnostics_workflow",
    file: ".github/workflows/desktop-release-diagnostics.yml",
    required: [
      "name: OPL Desktop Release Diagnostics",
      "workflow_dispatch:",
      "release_run_id:",
      "run_vm_diagnostic:",
      "build_standard_artifact:",
      "release_dmg_url:",
      "release_artifact_name:",
      "release_artifact_run_id:",
      "package_profile:",
      "diagnostic_scope:",
      "default: bootstrap_only",
      "inputs.diagnostic_scope",
      "temporary-standard-artifact",
      "inputs.release_artifact_run_id",
      "release-asset",
      "inputs.run_vm_diagnostic && 'vm' || 'metadata'",
      "permissions:",
      "actions: read",
      "contents: read",
      "diagnostic-inputs:",
      "Validate diagnostic workflow inputs",
      "build_standard_artifact only supports package_profile=standard",
      "build_standard_artifact must not be combined with release_dmg_url, release_artifact_name, or release_artifact_run_id",
      "npm run release:closeout --",
      "--artifact-profile diagnostics",
      "npm run release:actions-timing --",
      "standard-dmg-diagnostic-artifact:",
      "Build temporary standard DMG diagnostic artifact",
      "upload_installers_only: true",
      "vm-harness-diagnostics-standard-artifact:",
      "Run first-run VM diagnostic harness for temporary standard artifact",
      "inputs.build_standard_artifact && needs.diagnostic-inputs.result == 'success' && needs.standard-dmg-diagnostic-artifact.result == 'success'",
      "vm-harness-diagnostics-release-asset:",
      "Run first-run VM diagnostic harness for release asset",
      "!inputs.build_standard_artifact && needs.diagnostic-inputs.result == 'success'",
      "release_artifact_name: macos-build-arm64-dmg",
      "release_artifact_run_id: ${{ github.run_id }}",
      "release_artifact_name: ${{ inputs.release_artifact_name }}",
      "release_artifact_run_id: ${{ inputs.release_artifact_run_id != '' && inputs.release_artifact_run_id || inputs.release_run_id }}",
      "diagnostic_scope: ${{ inputs.diagnostic_scope }}",
      "uses: ./.github/workflows/opl-first-run-vm.yml",
      "release-diagnostics-${{ inputs.opl_version }}",
      "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a",
    ],
    forbidden: [
      "contents: write",
      "packages: write",
      "full-first-install-release",
      "gh release edit",
      "gh release upload",
      "npm run release:publish",
    ],
  },
];

const supersededLiveControlPlaneChecks = new Set([
  "framework_release_promotion_helper",
  "framework_release_promotion_receipt_validator",
  "release_cohort_plan_uses_canonical_dry_run_controller",
  "publish_script_repo",
  "full_release_workflow_uses_app_scripts",
  "desktop_release_workflow_uses_app_scripts",
  "release_notes_evidence_first",
  "release_closeout_script",
  "release_gate_reuse_plan_script",
  "release_preflight_script",
  "desktop_release_evidence_notes",
  "desktop_release_promote_verifies_before_publish",
  "desktop_release_full_addon_is_additive_only",
  "desktop_release_cleanup_drafts_workflow",
  "release_draft_cleanup_script_fail_closed",
  "desktop_release_diagnostics_workflow",
]);

export const releaseBoundaryChecks: ReleaseBoundaryCheck[] = [
  ...legacyReleaseBoundaryChecks.filter((check) => !supersededLiveControlPlaneChecks.has(check.id)),
  {
    id: "audited_optional_platform_publication_carrier",
    file: ".github/workflows/build-manual.yml",
    required: [
      "workflow_call:",
      "stable_optional_follower",
      "windows_preview_rc",
      "resolve-release-platform-matrix.ts",
      "--policy stable_optional",
      "opl_updater_version:",
      "require_windows_updater_assets:",
      "require_windows_authenticode:",
      "validate-windows-updater-assets.ts",
      "opl-windows-updater-assets.json",
      "opl-windows-authenticode-receipt.json",
      "*.exe.blockmap",
      "--policy \"$policy\"",
      "environment: ${{ needs.prepare-matrix.outputs.publication_mode == 'stable_optional_follower' && 'release-stable' || 'release-preview' }}",
      "Checkout exact App publisher source",
      "ref: ${{ needs.prepare-matrix.outputs.app_ref }}",
      "persist-credentials: false",
      "gh release upload \"$tag\" \"$asset_path\"",
      "immutable_release_capability_evidence:",
      "validateGithubImmutableReleaseCapabilityEvidence",
      "jq -S -n",
      "test -s \"$manifest_path\"",
      "immutable_release_capability_evidence_digest",
      "no retry is allowed",
      "opl_app_optional_platform_publication_receipt.v1",
      "base_stable_terminal_modified:false",
      "latest_modified:false",
      "start_distinct_operation_after_read_only_reconciliation",
    ],
    forbidden: [
      "--clobber",
      "make_latest: true",
      "gh run rerun",
      "gh run cancel",
      "\"repos/$GITHUB_REPOSITORY/immutable-releases\"",
      "inputs.matrix",
      "inputs.command",
      "inputs.os",
    ],
  },
  {
    id: "windows_stable_optional_reusable_build_gates",
    file: ".github/workflows/_build-reusable.yml",
    required: [
      "require_windows_updater_assets:",
      "require_windows_authenticode:",
      "config.nsis.differentialPackage=true",
      "validate-windows-updater-assets.ts",
      "opl-windows-updater-assets.json",
      "Get-AuthenticodeSignature",
      "TimeStamperCertificate",
      "opl-windows-authenticode-receipt.json",
      "-win-x64.exe.blockmap",
    ],
    forbidden: [
      "config.publish.provider=generic",
      "config.publish.url=",
    ],
  },
  {
    id: "automatic_optional_platform_follower",
    file: ".github/workflows/release-stable-post-success-followups.yml",
    required: [
      "workflow_run:",
      "publish-optional-platforms:",
      "optional_platforms_enabled",
      "uses: ./.github/workflows/build-manual.yml",
      "invocation_mode: stable_optional_follower",
      "platform_policy: stable_optional",
      "source_bundle_digest:",
      "workflow_dispatch:",
      "recover_exact_skipped_stable_optional_follower_v1",
      "opl_app_stable_optional_recovery_admission.v1",
      "full_successor:false",
    ],
    forbidden: [
      "continue-on-error:",
    ],
  },
  {
    id: "existing_base_optional_platform_follower",
    file: ".github/workflows/release-stable-optional-existing-base.yml",
    required: [
      "workflow_dispatch:",
      "optional_existing_base",
      "decodeStableOptionalExistingBaseCarrier",
      "publish-optional-platforms:",
      "invocation_mode: stable_optional_follower",
      "source_authority_kind: existing_base_source_qualification",
      "source_qualification_run_id",
      "base_release_target_commitish:",
      "publish_existing_v26_8_4_linux_windows_adjunct_v1",
      "v26.8.4",
      "linux-x64",
      "windows-x64",
      "standard_release:false",
      "base_release:false",
      "latest:false",
    ],
    forbidden: [
      "release-stable.yml/dispatches",
      "operation: standard",
      "operation: resume_standard",
      "operation: append_full",
      "make_latest:true",
    ],
  },
  {
    id: "release_bundle_package_scripts",
    file: "package.json",
    required: [
      '"release:framework-adapter": "node --experimental-strip-types scripts/framework-release-adapter.ts"',
      '"release:deadline": "node --experimental-strip-types scripts/release-operation-deadline.ts"',
      '"release:bind-standard": "node --experimental-strip-types scripts/bind-standard-release-track.ts"',
      '"release:historical-candidate-record:status": "node --experimental-strip-types scripts/validate-release-candidate-record.ts --status"',
      '"release:historical-bundle:status": "node --experimental-strip-types scripts/release-bundle.ts status"',
    ],
    forbidden: [
      '"release:stable":',
      '"release:operator":',
      '"release:publish":',
      '"release:bundle":',
      '"release:plan":',
      '"release:cohort-lock":',
      '"release:cohort-plan":',
      '"release:preflight":',
      '"release:closeout":',
      '"release:cleanup-drafts":',
      '"release:gate-reuse-plan":',
      '"release:cohort-manifest":',
      '"release:candidate-record":',
      '"release:candidate-record:resolve-owner":',
      '"release:candidate-record:validate":',
      '"release:candidate-record:status":',
      '"release:owner-candidate-record:verify":',
    ],
  },
  {
    id: "immutable_release_bundle_workflow",
    file: ".github/workflows/_release-bundle.yml",
    required: [
      "workflow_call:",
      "operation:",
      "default: standard",
      "startup-canary:",
      "freeze:",
      "standard-build:",
      "seal-standard-identity:",
      "checkpoint-standard:",
      "publish-standard:",
      "opl release freeze",
      "opl release build",
      "opl release checkpoint export",
      "uses: ./.github/workflows/_build-reusable.yml",
      "uses: ./.github/workflows/_release-standard-publish.yml",
      "bind-standard-release-track.ts",
      "standard_identity_sha256",
      "npm --prefix framework-source ci --ignore-scripts",
      "REQUESTED_APP_REF:",
      "App checkout differs from the admitted snapshot.",
      "Shell checkout differs from the admitted snapshot.",
      "Framework checkout differs from the admitted snapshot.",
      "require_macos_gatekeeper: true",
      "secrets: inherit",
    ],
    forbidden: [
      "workflow_dispatch:",
      "broker-admission",
      "--mode lookup",
      "id-token: write",
      "opl release reconcile",
      "environment: release-stable",
      "gh run rerun",
      "gh run cancel",
      "--clobber",
      "verify-release-broker-acceptance.ts",
      "release_attempt_id",
      "release_mutation_payload_sha256",
      "pre_api_admission_receipt_base64",
      "canonical_app_sha=",
      "canonical_shell_sha=",
      "canonical_framework_sha=",
      "standard-qualification:",
      "opl release verify",
    ],
  },
  {
    id: "standard_release_publish_workflow",
    file: ".github/workflows/_release-standard-publish.yml",
    required: [
      "workflow_call:",
      "description: standard or resume_standard",
      "startup-canary:",
      "pre-publication-admission:",
      "publish-standard-nonlatest:",
      "remote-digest-verify:",
      "publish-homebrew-standard:",
      "homebrew-standard-readback:",
      "activate-latest:",
      "environment: release-stable",
      "Verify sealed Standard identity",
      "standard_identity_sha256",
      "opl release publish",
      "opl release reconcile",
      "opl release status",
      "validate-standard-publication-input.ts",
      "stable-operation-publication-record.ts create",
      "publication_record_args=(--publication-record \"$record\")",
      "Activate Latest after exact remote parity",
    ],
    forbidden: [
      "workflow_dispatch:",
      "opl release freeze",
      "opl release build",
      "verify-release-broker-acceptance.ts",
      "verify-release-session-lease.ts",
      "gh run rerun",
      "gh run cancel",
      "--clobber",
      "updater-upgrade-qualification:",
      "updater-upgrade-qualification-highest:",
      "homebrew-standard-vm:",
    ],
  },
  {
    id: "full_release_append_workflow",
    file: ".github/workflows/_release-full-addon.yml",
    required: [
      "workflow_call:",
      "default: append_full",
      "startup-canary:",
      "restore-standard:",
      "full-build:",
      "full-qualification:",
      "checkpoint-full:",
      "publish-full:",
      "Append exact Full bytes to the mutable Standard Release",
      "standard_tag='${{ needs.restore-standard.outputs.target_standard_release_tag }}'",
      "--pattern opl-release-attestation.json",
      "--standard-attestation \"$standard_attestation\"",
      "opl_app_full_append_boundary_receipt.v1",
      "carrier:{kind:\"same_standard_release_assets\"",
      "full-read-only-reconcile.json",
      "test \"$(jq -r .mutation_attempted full-read-only-reconcile.json)\" = false",
      "standard_updater_metadata_modified:false",
      "latest_modified:false",
    ],
    forbidden: [
      "workflow_dispatch:",
      "uses: ./.github/workflows/opl-updater-upgrade-vm.yml",
      "activate-latest:",
      "Activate Latest",
      "verify-release-broker-acceptance.ts",
      "verify-release-session-lease.ts",
      "gh run rerun",
      "gh run cancel",
      "--clobber",
      "gh release create",
      "adjunct_tag=",
      "--publication-record",
    ],
  },
  {
    id: "stable_release_bundle_entry",
    file: ".github/workflows/release-stable.yml",
    required: [
      "workflow_dispatch:",
      "- standard",
      "- resume_standard",
      "- append_full",
      "uses: ./.github/workflows/_release-bundle.yml",
      "uses: ./.github/workflows/_release-standard-publish.yml",
      "uses: ./.github/workflows/_release-full-addon.yml",
      "channel: stable",
      "protected-operation-admission:",
      "admission:",
      "test \"$GITHUB_RUN_ATTEMPT\" = 1",
      "authority_id:",
      "authority_carrier:",
      "authority_digest:",
      "Reject bare or rerun Stable request before expensive work",
      "stable-operation-control.ts decode-carrier",
      "stable-operation-control.ts verify-authority",
      "stable-operation-control.ts materialize-evidence",
      "stable-operation-control.ts verify-executor",
      "git -C app-source checkout --detach \"$app_sha\"",
      "release-dispatch-guard.ts verify-evidence",
      "release-dispatch-guard.ts preflight",
      "--current-run-id \"$GITHUB_RUN_ID\"",
      "stable-operation-control.ts bind",
      "stable-operation-control.ts verify",
      "Upload immutable operation control evidence",
      "opl-stable-operation-control-${{ github.run_id }}",
      "environment: release-stable",
      "authority_id:",
      "operation_id:",
      "authority_carrier:",
      "authority_digest:",
      "stable-operation-control.ts decode-carrier",
      "stable-operation-control.ts bind",
      "Verify protected Apple credentials in the Stable entry",
      "stable-release-admission-manifest.ts create",
      "actions/runs/$GITHUB_RUN_ID\" --jq .created_at",
      "release-operation-deadline.ts resolve",
      "Upload immutable operation admission",
      "needs: [admission, protected-operation-admission, stable-admission-manifest]",
      "app_ref: ${{ needs.protected-operation-admission.outputs.app_ref }}",
      "shell_ref: ${{ needs.protected-operation-admission.outputs.shell_ref }}",
      "framework_ref: ${{ needs.protected-operation-admission.outputs.framework_ref }}",
      "stable_operation_control_artifact: opl-stable-operation-control-${{ github.run_id }}",
      "stable_operation_control_digest: ${{ needs.protected-operation-admission.outputs.control_digest }}",
      "group: opl-release-bundle-global",
      "cancel-in-progress: false",
    ],
    forbidden: [
      "schedule:",
      "release-broker",
      "verify-release-broker",
      "verify-release-session-lease",
      "release_attempt_id",
      "release_mutation_payload_sha256",
      "pre_api_admission_receipt_base64",
      "packages: write",
      "canonical_app_sha=",
      "canonical_shell_sha=",
      "canonical_framework_sha=",
      "gh release",
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
      "uses: ./.github/workflows/release-source-qualification.yml",
      "source-qualification-receipt.ts",
      "validate-source-qualification-receipt.ts",
    ],
  },
  {
    id: "manual_full_preview_protected_entry",
    file: ".github/workflows/release-manual-full-preview.yml",
    required: [
      "workflow_dispatch:",
      "- publish",
      "- cleanup",
      "handoff_nonce:",
      "handoff_manifest_sha256:",
      "OPL_MANUAL_PREVIEW_INGRESS_ROOT",
      "runs-on: [self-hosted, macOS, ARM64, opl-gui-vm]",
      "environment: release-stable",
      "group: opl-release-bundle-global",
      "cancel-in-progress: false",
      "test \"$GITHUB_RUN_ATTEMPT\" = 1",
      "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a",
      "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c",
      "artifact-ids: ${{ needs.ingress.outputs.artifact_id }}",
      "compression-level: 0",
      "overwrite: false",
      "manual-full-preview-release.ts ingest",
      "manual-full-preview-release.ts verify-artifact",
      "manual-full-preview-release.ts mutate",
      "mutation_retry_performed:false",
    ],
    forbidden: [
      "source_run_id",
      "opl release",
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
      "latest-arm64-mac.yml",
      "update-homebrew",
      "--clobber",
    ],
  },
  {
    id: "manual_full_preview_executor",
    file: "scripts/manual-full-preview-release.ts",
    required: [
      "opl_manual_full_preview_manifest.v1",
      "MANUAL_USABLE_DELIVERED",
      "minimum_host_qa",
      "manual-full-preview-${version}-m1-${sourceLockSha256.slice(0, 12)}",
      "make_latest: 'false'",
      "https://uploads.github.com/repos/${repo}/releases/${releaseId}/assets",
      "artifactDigestRef = `sha256:${input.artifactDigest}`",
      "outcome is unknown after three read-only inspections; mutation was not retried",
      "M2 and Stable append/readback receipts do not bind the same Bundle",
      "exact required formal Stable asset set",
      "deleteRelease",
      "deleteTag",
      "Preview publication changed GitHub Latest",
      "Stable Release ${handoff.stableTag} is not GitHub Latest",
    ],
    forbidden: [
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
      "make_latest: 'true'",
      "--clobber",
      "opl release",
    ],
  },
  {
    id: "nightly_standard_release_entry",
    file: ".github/workflows/release-nightly.yml",
    required: [
      "schedule:",
      "cron: '17 19 * * *'",
      "workflow_dispatch:",
      "operator_confirmation:",
      "publish_nonlatest_nightly",
      "group: opl-standard-nightly",
      "uses: ./.github/workflows/_build-reusable.yml",
      "require_macos_gatekeeper: false",
      "resolve-nightly-release-request.ts",
      "nightly-release-qualification.ts",
      "nightly-release-notes.ts",
      "nightly-notes-baseline.json",
      "nightly-notes-evidence.json",
      "nightly-release-publisher.ts",
      "environment: release-nightly",
    ],
    forbidden: [
      "opl-release-bundle-global",
      "uses: ./.github/workflows/_release-bundle.yml",
      "uses: ./.github/workflows/opl-first-run-vm.yml",
      "require_macos_gatekeeper: true",
      "uses: ./.github/workflows/_release-full-addon.yml",
      "uses: ./.github/workflows/release-webui",
      "make_latest: true",
    ],
  },
  {
    id: "nightly_homebrew_follower",
    file: ".github/workflows/release-nightly-homebrew-follower.yml",
    required: [
      "workflow_run:",
      "- OPL Standard Nightly Release",
      "environment: release-nightly",
      "OPL_HOMEBREW_TAP_DEPLOY_KEY",
      "git@github.com:${tap_repo}.git",
      "IdentitiesOnly=yes",
      "StrictHostKeyChecking=yes",
      "Casks/one-person-lab-nightly.rb",
      "git -C tap-source push --no-force",
      "retry_performed:false",
    ],
    forbidden: [
      "workflow_dispatch:",
      "uses: ./.github/workflows/opl-first-run-vm.yml",
      "Casks/one-person-lab-full.rb",
      "make_latest: true",
      "gh workflow run",
      "gh run rerun",
      "OPL_HOMEBREW_TAP_TOKEN",
      "environment: release-stable",
    ],
  },
  {
    id: "nightly_sampled_vm_follower",
    file: ".github/workflows/release-nightly-sampled-vm.yml",
    required: [
      "workflow_run:",
      "- OPL Standard Nightly Release",
      "TZ=Asia/Shanghai date +%u",
      "uses: ./.github/workflows/opl-first-run-vm.yml",
      "package_profile: standard",
      "require_macos_gatekeeper: false",
    ],
    forbidden: [
      "workflow_dispatch:",
      "contents: write",
      "packages: write",
      "update-homebrew",
      "make_latest: true",
    ],
  },
  {
    id: "release_bundle_no_mutation_canary",
    file: ".github/workflows/release-bundle-canary.yml",
    required: [
      "permissions:",
      "contents: read",
      "actions: read",
      "schedule:",
      "cron: '0 13 * * *'",
      "workflow_dispatch:",
      "group: opl-release-validation-canary-${{ github.ref }}",
      "cancel-in-progress: true",
      "mode: canary",
      "uses: ./.github/workflows/_release-bundle.yml",
      "uses: ./.github/workflows/_release-standard-publish.yml",
      "uses: ./.github/workflows/_release-full-addon.yml",
      "uses: ./.github/workflows/_build-reusable.yml",
      "uses: ./.github/workflows/opl-first-run-vm.yml",
      "uses: ./.github/workflows/_release-webui-carrier.yml",
      "uses: ./.github/workflows/release-webui-stable.yml",
      "uses: ./.github/workflows/opl-updater-upgrade-vm.yml",
      "uses: ./.github/workflows/full-first-install-release.yml",
      "tests/release/release-bundle-workflow-cutover.test.ts",
      "packages: write",
    ],
    forbidden: [
      "push:",
      "pull_request:",
      "contents: write",
      "secrets:",
      "mode: execute",
      "channel: nightly",
      "opl-release-bundle-global",
      "gh release",
      "gh workflow run",
      "gh run rerun",
      "gh run cancel",
    ],
  },
  ...[
    ["desktop_release", ".github/workflows/desktop-release.yml"],
    ["desktop_release_promote", ".github/workflows/desktop-release-promote.yml"],
    ["desktop_release_full_addon", ".github/workflows/desktop-release-full-addon.yml"],
    ["desktop_release_cleanup", ".github/workflows/desktop-release-cleanup-drafts.yml"],
  ].map(([id, file]) => ({
    id: `${id}_retired_absent`,
    file,
    retired: true,
  })),
  {
    id: "desktop_release_diagnostics_read_only",
    file: ".github/workflows/desktop-release-diagnostics.yml",
    required: [
      "workflow_call:",
      "actions: read",
      "contents: read",
      "uses: ./.github/workflows/opl-first-run-vm.yml",
    ],
    forbidden: ["workflow_dispatch:", "contents: write", "packages: write", "gh release upload"],
  },
];

const windowsPreviewOnlyCheckIds = new Set([
  'docker_webui_clean_windows_vm_workflow',
  'docker_webui_clean_windows_dispatch_helper',
  'docker_webui_clean_windows_dispatch_npm_script',
  'docker_webui_clean_windows_runner_bootstrap_runbook',
]);

export function releaseBoundaryChecksForProfile(
  profile = releaseValidationProfile(),
): ReleaseBoundaryCheck[] {
  if (profile === 'aggregate') return releaseBoundaryChecks;
  if (profile === 'stable') {
    return releaseBoundaryChecks.filter((check) => !windowsPreviewOnlyCheckIds.has(check.id));
  }
  return releaseBoundaryChecks.filter((check) => windowsPreviewOnlyCheckIds.has(check.id));
}
